const { prisma } = require("../db/prisma");
const {
  CreateClientMessageDto,
  CreateCoachMessageDto,
  CreateAiMessageDto,
  MarkClientMessageHandledDto,
  GetMessagesByConversationDto,
} = require("../dtos/message.dto");

const { MessageSender, MessageContentType } = require("@prisma/client");
const {
  touchConversation,
} = require("./conversation.service");

/* =============================================================================
   CREATE MESSAGES
============================================================================= */


const createClientMessage = async (payload) => {
  const {
    conversationId,
    contentType,
    text,
    media,
    sourceMessageId,
  } = CreateClientMessageDto.parse(payload);

  const message = await prisma.message.create({
    data: {
      conversationId,
      sender: MessageSender.CLIENT,
      contentType,
      text,
      ...(media || {}),
      sourceMessageId,
    },
  });

  await touchConversation(conversationId);
  return message;
};


const createCoachMessage = async (payload) => {
  const {
    conversationId,
    contentType,
    text,
    media,
  } = CreateCoachMessageDto.parse(payload);

  const message = await prisma.message.create({
    data: {
      conversationId,
      sender: MessageSender.COACH,
      contentType,
      text,
      ...(media || {}),
    },
  });

  await touchConversation(conversationId);
  return message;
};

const createAiMessage = async (payload) => {
  const {
    conversationId,
    text,
    autoGenerated = true,
  } = CreateAiMessageDto.parse(payload);

  const message = await prisma.message.create({
    data: {
      conversationId,
      sender: MessageSender.AI,
      contentType: MessageContentType.TEXT,
      text,
      autoGenerated,
    },
  });

  await touchConversation(conversationId);
  return message;
};

/* =============================================================================
   CLIENT MESSAGE HANDLING
============================================================================= */

const markClientMessageHandled = async ({ messageId, handledBy }) => {
  return prisma.message.update({
    where: { id: messageId },
    data: {
      handledAt: new Date(),
      handledBy,
    },
  });
};

/* =============================================================================
   QUERIES
============================================================================= */
const getMessagesByConversation = async (payload) => {
  const { conversationId } =
    GetMessagesByConversationDto.parse(payload);

  return prisma.message.findMany({
    where: { conversationId },
    orderBy: { createdAt: "asc" },
  });
};

module.exports = {
  createClientMessage,
  createCoachMessage,
  createAiMessage,
  markClientMessageHandled,
  getMessagesByConversation,
};
