const { prisma } = require("../db/prisma");
const { getUserByPhone } = require("../clients/idm.client");
const { getOrCreateConversation } = require("./conversation.service");
const {
  createClientMessage,
  createAiMessage,
} = require("./message.service");
const { triageClientMessage } = require("./aiTriage.service");
const { sendMessageExternally } = require("./sendMessageExternally.service");

/**
 * Internal orchestration ONLY
 */
const handleIncomingMessage = async ({
  fromPhone,
  toPhone,
  channel,
  contentType,
  text,
  media,
  sourceMessageId,
}) => {
  console.log("🚀 handleIncomingMessage START", {
    fromPhone,
    toPhone,
    channel,
    contentType,
    hasText: !!text,
    hasMedia: !!media,
    sourceMessageId,
  });

  /* =========================
     1️⃣ Resolve identities
  ========================= */
  console.log("➡️ [1] Resolving identities");

  let fromUser, toUser;
  try {
    fromUser = await getUserByPhone(fromPhone);
    console.log("✅ [1.1] fromUser resolved", fromUser);

    toUser = await getUserByPhone(toPhone);
    console.log("✅ [1.2] toUser resolved", toUser);
  } catch (err) {
    console.error("💥 [1] Failed resolving identities", err);
    throw err;
  }

  if (!fromUser || !toUser) {
    console.error("💥 [1] Unknown external identity", {
      fromUser,
      toUser,
    });
    throw new Error("Unknown external identity");
  }

  if (fromUser.role !== "client") {
    console.error("💥 [1] fromUser is not CLIENT", fromUser.role);
    throw new Error("Incoming message must be from CLIENT");
  }

  if (toUser.role !== "coach") {
    console.error("💥 [1] toUser is not COACH", toUser.role);
    throw new Error("Incoming message must be to COACH");
  }

  const clientId = fromUser.id;
  const coachId = toUser.id;

  /* =========================
     2️⃣ Conversation
  ========================= */
  console.log("➡️ [2] Resolving conversation", {
    clientId,
    coachId,
    channel,
  });

  let conversation;
  try {
    conversation = await getOrCreateConversation({
      coachId,
      clientId,
      channel,
    });
    console.log("✅ [2] Conversation resolved", {
      id: conversation.id,
    });
  } catch (err) {
    console.error("💥 [2] Failed resolving conversation", err);
    throw err;
  }

  /* =========================
     3️⃣ CLIENT Message
  ========================= */
  console.log("➡️ [3] Creating client message");

  let clientMessage;
  try {
    clientMessage = await createClientMessage({
      conversationId: conversation.id,
      contentType,
      text,
      media,
      sourceMessageId,
    });
    console.log("✅ [3] Client message created", {
      id: clientMessage.id,
    });
  } catch (err) {
    console.error("💥 [3] Failed creating client message", err);
    throw err;
  }

  /* =========================
     4️⃣ AI Triage
  ========================= */
  console.log("➡️ [4] Running AI triage (MCP)", {
    messageId: clientMessage.id,
  });

  try {
    await triageClientMessage({ messageId: clientMessage.id });
    console.log("✅ [4] AI triage finished");
  } catch (err) {
    console.error("💥 [4] AI triage failed", err);
    throw err;
  }

  let updatedMessage;
  try {
    updatedMessage = await prisma.message.findUnique({
      where: { id: clientMessage.id },
    });
    console.log("✅ [4.1] Message reloaded after AI", {
      aiDecision: updatedMessage?.aiDecision,
      hasSuggestedReply: !!updatedMessage?.aiSuggestedReply,
    });
  } catch (err) {
    console.error("💥 [4.1] Failed loading message after AI", err);
    throw err;
  }

  /* =========================
     5️⃣ AUTO_REPLY execution
  ========================= */
  if (
    updatedMessage?.aiDecision === "AUTO_REPLY" &&
    updatedMessage?.aiSuggestedReply
  ) {
    console.log("➡️ [5] AUTO_REPLY path triggered");

    let aiMessage;
    try {
      aiMessage = await createAiMessage({
        conversationId: conversation.id,
        text: updatedMessage.aiSuggestedReply,
        autoGenerated: true,
      });
      console.log("✅ [5.1] AI message created", {
        id: aiMessage.id,
      });
    } catch (err) {
      console.error("💥 [5.1] Failed creating AI message", err);
      throw err;
    }

    try {
      console.log("➡️ [5.2] Sending AI message externally", {
        messageId: aiMessage.id,
      });
      await sendMessageExternally(aiMessage.id);
      console.log("✅ [5.2] AI message sent externally");
    } catch (err) {
      console.error("💥 [5.2] Failed sending AI message externally", err);
      throw err;
    }
  } else {
    console.log("ℹ️ [5] No AUTO_REPLY – nothing to send");
  }

  console.log("🏁 handleIncomingMessage END – SUCCESS");
  return { ok: true };
};

module.exports = { handleIncomingMessage };
