const { prisma } = require("../db/prisma");

const { IncomingWebhookMessageDto } = require("../dtos/webhook.dto");

const { getUserByPhone } = require("../clients/idm.client");
const { getOrCreateConversation } = require("./conversation.service");
const {createClientMessage,createAiMessage,} = require("./message.service");
const { triageClientMessage } = require("./aiTriage.service");

const {sendMessageExternally} = require("./sendMessageExternally.service");

/**
 * טיפול בהודעה נכנסת (Telegram / WhatsApp / App)
 *
 * אחריות:
 * - orchestration בלבד
 * - resolve identities
 * - create messages
 * - execute AUTO_REPLY
 */
const handleIncomingMessage = async (payload) => {
  const {
    fromPhone,
    toPhone,
    channel,
    contentType,
    text,
    media,
    sourceMessageId,
  } = IncomingWebhookMessageDto.parse(payload);

  /* =========================
     1️⃣ Resolve identities (IDM)
  ========================= */

  const fromUser = await getUserByPhone(fromPhone);
  const toUser = await getUserByPhone(toPhone);

  if (!fromUser || !toUser) {
    throw new Error("Unknown external identity");
  }

  // חוק ברזל
  if (fromUser.role !== "CLIENT") {
    throw new Error("Incoming message must be from CLIENT");
  }
  if (toUser.role !== "COACH") {
    throw new Error("Incoming message must be to COACH");
  }

  const clientId = fromUser.id;
  const coachId = toUser.id;

  /* =========================
     2️⃣ Conversation
  ========================= */

  const conversation = await getOrCreateConversation({
    coachId,
    clientId,
    channel,
  });

  /* =========================
     3️⃣ CLIENT Message
  ========================= */

  const clientMessage = await createClientMessage({
    conversationId: conversation.id,
    contentType,
    text,
    media,
    sourceMessageId,
  });

  /* =========================
     4️⃣ AI Triage (Decision)
  ========================= */

  await triageClientMessage({ messageId: clientMessage.id });

  const updatedMessage = await prisma.message.findUnique({
    where: { id: clientMessage.id },
  });

  /* =========================
     5️⃣ EXECUTION (AUTO_REPLY)
  ========================= */

  if (
    updatedMessage.aiDecision === "AUTO_REPLY" &&
    updatedMessage.aiSuggestedReply
  ) {
    // 5.1 create AI message (internal)
    const aiMessage = await createAiMessage({
      conversationId: conversation.id,
      text: updatedMessage.aiSuggestedReply,
      autoGenerated: true,
    });

    // 5.2 send externally (Telegram)
    await sendMessageExternally(aiMessage.id);
  }

  /* =========================
     DONE
  ========================= */

  return { ok: true };
};

module.exports = { handleIncomingMessage };
