const { prisma } = require("../db/prisma");

const { getUserByPhone } = require("../clients/idm.client");
const { getOrCreateConversation } = require("./conversation.service");
const {
  createClientMessage,
  createAiMessage,
} = require("./message.service");
const { triageClientMessage } = require("./aiTriage.service");
const { sendMessageExternally } = require("./sendMessageExternally.service");

/**
 * Internal orchestration ONLY
 */
const handleIncomingMessage = async ({
  fromPhone,
  toPhone,
  channel,
  contentType,
  text,
  media,
  sourceMessageId,
}) => {
  /* =========================
     1️⃣ Resolve identities
  ========================= */
 

  const fromUser = await getUserByPhone(fromPhone);
  const toUser = await getUserByPhone(toPhone);

  console.log("👤 fromUser:", fromUser);
  console.log("👤 toUser:", toUser);
  
  if (!fromUser || !toUser) {
    throw new Error("Unknown external identity");
  }

  if (fromUser.role !== "client") {
    throw new Error("Incoming message must be from CLIENT");
  }

  if (toUser.role !== "coach") {
    throw new Error("Incoming message must be to COACH");
  }

  const clientId = fromUser.id;
  const coachId = toUser.id;

  /* =========================
     2️⃣ Conversation
  ========================= */

  const conversation = await getOrCreateConversation({
    coachId,
    clientId,
    channel,
  });

  /* =========================
     3️⃣ CLIENT Message
  ========================= */

  const clientMessage = await createClientMessage({
    conversationId: conversation.id,
    contentType,
    text,
    media,
    sourceMessageId,
  });

  /* =========================
     4️⃣ AI Triage
  ========================= */

  await triageClientMessage({ messageId: clientMessage.id });

  const updatedMessage = await prisma.message.findUnique({
    where: { id: clientMessage.id },
  });

  /* =========================
     5️⃣ AUTO_REPLY execution
  ========================= */

  if (
    updatedMessage.aiDecision === "AUTO_REPLY" &&
    updatedMessage.aiSuggestedReply
  ) {
    const aiMessage = await createAiMessage({
      conversationId: conversation.id,
      text: updatedMessage.aiSuggestedReply,
      autoGenerated: true,
    });

    await sendMessageExternally(aiMessage.id);
  }

  return { ok: true };
};

module.exports = { handleIncomingMessage };
