/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type AIDecisionEnum = typeof AIDecisionEnum[keyof typeof AIDecisionEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AIDecisionEnum = {
  AUTO_REPLY: 'AUTO_REPLY',
  COACH_REPLY: 'COACH_REPLY',
} as const;
