/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type BodyTypeEnum = typeof BodyTypeEnum[keyof typeof BodyTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BodyTypeEnum = {
  ECTO: 'ECTO',
  ENDO: 'ENDO',
} as const;
