/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuUpdateRequestDtoMealsToUpdateItemItemsToAddItem } from './clientMenuUpdateRequestDtoMealsToUpdateItemItemsToAddItem';
import type { ClientMenuUpdateRequestDtoMealsToUpdateItemItemsToUpdateItem } from './clientMenuUpdateRequestDtoMealsToUpdateItemItemsToUpdateItem';
import type { ClientMenuUpdateRequestDtoMealsToUpdateItemItemsToDeleteItem } from './clientMenuUpdateRequestDtoMealsToUpdateItemItemsToDeleteItem';

export type ClientMenuUpdateRequestDtoMealsToUpdateItem = {
  id: string;
  name?: string;
  /** @nullable */
  selectedOptionId?: string | null;
  totalCalories?: number;
  itemsToAdd?: ClientMenuUpdateRequestDtoMealsToUpdateItemItemsToAddItem[];
  itemsToUpdate?: ClientMenuUpdateRequestDtoMealsToUpdateItemItemsToUpdateItem[];
  itemsToDelete?: ClientMenuUpdateRequestDtoMealsToUpdateItemItemsToDeleteItem[];
};
