/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type ClientMenuCreateRequestDtoType = typeof ClientMenuCreateRequestDtoType[keyof typeof ClientMenuCreateRequestDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientMenuCreateRequestDtoType = {
  TRAINING: 'TRAINING',
  REST: 'REST',
} as const;
