/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientsListResponseDtoDataItem } from './clientsListResponseDtoDataItem';

export interface ClientsListResponseDto {
  map(buildClient: (c: import("./clientListItemDto").ClientListItemDto) => import("@/types/client").ClientExtended): import("@/types/client").ClientExtended[] | PromiseLike<import("@/types/client").ClientExtended[]>;
  data: ClientsListResponseDtoDataItem[];
}
