/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuListResponseDtoDataItemMealsItem } from './clientMenuListResponseDtoDataItemMealsItem';
import type { ClientMenuListResponseDtoDataItemVitaminsItem } from './clientMenuListResponseDtoDataItemVitaminsItem';

export type ClientMenuListResponseDtoDataItem = {
  id: string;
  clientId: string;
  coachId: string;
  name: string;
  type: string;
  /** @nullable */
  notes: string | null;
  isActive: boolean;
  /** @nullable */
  startDate: string | null;
  /** @nullable */
  endDate: string | null;
  totalCalories: number;
  meals: ClientMenuListResponseDtoDataItemMealsItem[];
  vitamins: ClientMenuListResponseDtoDataItemVitaminsItem[];
};
