/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientsListResponseDtoDataItemGoals } from './clientsListResponseDtoDataItemGoals';
import type { ClientsListResponseDtoDataItemActivityLevel } from './clientsListResponseDtoDataItemActivityLevel';

export type ClientsListResponseDtoDataItem = {
  id: string;
  name: string;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  profileImageUrl: string | null;
  /** @nullable */
  gender: string | null;
  /** @nullable */
  age: number | null;
  /** @nullable */
  height: number | null;
  /** @nullable */
  weight: number | null;
  /** @nullable */
  goals: ClientsListResponseDtoDataItemGoals;
  /** @nullable */
  activityLevel: ClientsListResponseDtoDataItemActivityLevel;
  /** @nullable */
  creationDate: string | null;
  /** @nullable */
  city: string | null;
  /** @nullable */
  address: string | null;
};
