/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuResponseDtoMealsItem } from './clientMenuResponseDtoMealsItem';
import type { ClientMenuResponseDtoVitaminsItem } from './clientMenuResponseDtoVitaminsItem';

export interface ClientMenuResponseDto {
  id: string;
  clientId: string;
  coachId: string;
  name: string;
  type: string;
  /** @nullable */
  notes: string | null;
  isActive: boolean;
  /** @nullable */
  startDate: string | null;
  /** @nullable */
  endDate: string | null;
  totalCalories: number;
  meals: ClientMenuResponseDtoMealsItem[];
  vitamins: ClientMenuResponseDtoVitaminsItem[];
}
