/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuResponseDtoMealsItemOptionsItem } from './clientMenuResponseDtoMealsItemOptionsItem';
import type { ClientMenuResponseDtoMealsItemItemsItem } from './clientMenuResponseDtoMealsItemItemsItem';

export type ClientMenuResponseDtoMealsItem = {
  id: string;
  name: string;
  /** @nullable */
  selectedOptionId: string | null;
  options: ClientMenuResponseDtoMealsItemOptionsItem[];
  items: ClientMenuResponseDtoMealsItemItemsItem[];
};
