/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuListResponseDtoDataItemMealsItemOptionsItem } from './clientMenuListResponseDtoDataItemMealsItemOptionsItem';

export type ClientMenuListResponseDtoDataItemMealsItem = {
  id: string;
  name: string;
  /** @nullable */
  notes: string | null;
  totalCalories: number;
  /** @nullable */
  selectedOptionId: string | null;
  options: ClientMenuListResponseDtoDataItemMealsItemOptionsItem[];
};
