/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export interface ClientMenuCreateRequestDto {
  name: string;
  type: string;
  allowedDaysPerWeek?: number;
  /** @nullable */
  notes?: string | null;
  startDate?: string;
  endDate?: string;
}
