/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuResponseDtoMealsItemOptionsItemMealTemplateItemsItem } from './clientMenuResponseDtoMealsItemOptionsItemMealTemplateItemsItem';

export type ClientMenuResponseDtoMealsItemOptionsItemMealTemplate = {
  id: string;
  name: string;
  kind: string;
  /** @nullable */
  totalCalories?: number | null;
  items: ClientMenuResponseDtoMealsItemOptionsItemMealTemplateItemsItem[];
};
