/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuCreateRequestDtoType } from './clientMenuCreateRequestDtoType';

export interface ClientMenuCreateRequestDto {
  clientId: string;
  name: string;
  type: ClientMenuCreateRequestDtoType;
  /** @nullable */
  notes?: string | null;
  startDate?: string;
  endDate?: string;
}
