/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuResponseDtoMealsItemItemsItemFoodItem } from './clientMenuResponseDtoMealsItemItemsItemFoodItem';

export type ClientMenuResponseDtoMealsItemItemsItem = {
  id: string;
  quantity: number;
  calories: number;
  /** @nullable */
  notes: string | null;
  foodItem: ClientMenuResponseDtoMealsItemItemsItemFoodItem;
};
