/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuUpdateRequestDtoMealOptionsToUpdateItemItemsToAddItem } from './clientMenuUpdateRequestDtoMealOptionsToUpdateItemItemsToAddItem';
import type { ClientMenuUpdateRequestDtoMealOptionsToUpdateItemItemsToUpdateItem } from './clientMenuUpdateRequestDtoMealOptionsToUpdateItemItemsToUpdateItem';
import type { ClientMenuUpdateRequestDtoMealOptionsToUpdateItemItemsToDeleteItem } from './clientMenuUpdateRequestDtoMealOptionsToUpdateItemItemsToDeleteItem';

export type ClientMenuUpdateRequestDtoMealOptionsToUpdateItem = {
  id: string;
  /** @nullable */
  name?: string | null;
  orderIndex?: number;
  itemsToAdd?: ClientMenuUpdateRequestDtoMealOptionsToUpdateItemItemsToAddItem[];
  itemsToUpdate?: ClientMenuUpdateRequestDtoMealOptionsToUpdateItemItemsToUpdateItem[];
  itemsToDelete?: ClientMenuUpdateRequestDtoMealOptionsToUpdateItemItemsToDeleteItem[];
};
