/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuUpdateRequestDtoMealsToUpdateItemOptionsToUpdateItemItemsToAddItem } from './clientMenuUpdateRequestDtoMealsToUpdateItemOptionsToUpdateItemItemsToAddItem';
import type { ClientMenuUpdateRequestDtoMealsToUpdateItemOptionsToUpdateItemItemsToUpdateItem } from './clientMenuUpdateRequestDtoMealsToUpdateItemOptionsToUpdateItemItemsToUpdateItem';
import type { ClientMenuUpdateRequestDtoMealsToUpdateItemOptionsToUpdateItemItemsToDeleteItem } from './clientMenuUpdateRequestDtoMealsToUpdateItemOptionsToUpdateItemItemsToDeleteItem';

export type ClientMenuUpdateRequestDtoMealsToUpdateItemOptionsToUpdateItem = {
  id: string;
  /** @nullable */
  name?: string | null;
  orderIndex?: number;
  itemsToAdd?: ClientMenuUpdateRequestDtoMealsToUpdateItemOptionsToUpdateItemItemsToAddItem[];
  itemsToUpdate?: ClientMenuUpdateRequestDtoMealsToUpdateItemOptionsToUpdateItemItemsToUpdateItem[];
  itemsToDelete?: ClientMenuUpdateRequestDtoMealsToUpdateItemOptionsToUpdateItemItemsToDeleteItem[];
};
