/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type ClientMenuListResponseDtoDataItemVitaminsItem = {
  id: string;
  /** @nullable */
  vitaminId: string | null;
  name: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  notes: string | null;
};
