/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuResponseDtoMealsItemOptionsItemMealTemplateItemsItemFoodItem } from './clientMenuResponseDtoMealsItemOptionsItemMealTemplateItemsItemFoodItem';

export type ClientMenuResponseDtoMealsItemOptionsItemMealTemplateItemsItem = {
  id: string;
  role: string;
  defaultGrams: number;
  /** @nullable */
  notes: string | null;
  foodItem: ClientMenuResponseDtoMealsItemOptionsItemMealTemplateItemsItemFoodItem;
};
