/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuCreateFromTemplateRequestDtoSelectedOptionsItem } from './clientMenuCreateFromTemplateRequestDtoSelectedOptionsItem';

export interface ClientMenuCreateFromTemplateRequestDto {
  templateMenuId: string;
  clientId: string;
  coachId: string;
  name?: string;
  selectedOptions?: ClientMenuCreateFromTemplateRequestDtoSelectedOptionsItem[];
}
