/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type ClientMenuUpdateRequestDtoMealsToUpdateItemItemsToUpdateItem = {
  id: string;
  quantity?: number;
  calories?: number;
  /** @nullable */
  notes?: string | null;
};
