/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuUpdateRequestDtoMealsToAddItem } from './clientMenuUpdateRequestDtoMealsToAddItem';
import type { ClientMenuUpdateRequestDtoMealsToUpdateItem } from './clientMenuUpdateRequestDtoMealsToUpdateItem';
import type { ClientMenuUpdateRequestDtoMealsToDeleteItem } from './clientMenuUpdateRequestDtoMealsToDeleteItem';
import type { ClientMenuUpdateRequestDtoMealOptionsToAddItem } from './clientMenuUpdateRequestDtoMealOptionsToAddItem';
import type { ClientMenuUpdateRequestDtoMealOptionsToUpdateItem } from './clientMenuUpdateRequestDtoMealOptionsToUpdateItem';
import type { ClientMenuUpdateRequestDtoMealOptionsToDeleteItem } from './clientMenuUpdateRequestDtoMealOptionsToDeleteItem';
import type { ClientMenuUpdateRequestDtoVitaminsToAddItem } from './clientMenuUpdateRequestDtoVitaminsToAddItem';
import type { ClientMenuUpdateRequestDtoVitaminsToUpdateItem } from './clientMenuUpdateRequestDtoVitaminsToUpdateItem';
import type { ClientMenuUpdateRequestDtoVitaminsToDeleteItem } from './clientMenuUpdateRequestDtoVitaminsToDeleteItem';

export interface ClientMenuUpdateRequestDto {
  name?: string;
  type?: string;
  /** @nullable */
  notes?: string | null;
  isActive?: boolean;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
  mealsToAdd?: ClientMenuUpdateRequestDtoMealsToAddItem[];
  mealsToUpdate?: ClientMenuUpdateRequestDtoMealsToUpdateItem[];
  mealsToDelete?: ClientMenuUpdateRequestDtoMealsToDeleteItem[];
  mealOptionsToAdd?: ClientMenuUpdateRequestDtoMealOptionsToAddItem[];
  mealOptionsToUpdate?: ClientMenuUpdateRequestDtoMealOptionsToUpdateItem[];
  mealOptionsToDelete?: ClientMenuUpdateRequestDtoMealOptionsToDeleteItem[];
  vitaminsToAdd?: ClientMenuUpdateRequestDtoVitaminsToAddItem[];
  vitaminsToUpdate?: ClientMenuUpdateRequestDtoVitaminsToUpdateItem[];
  vitaminsToDelete?: ClientMenuUpdateRequestDtoVitaminsToDeleteItem[];
}
