/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuListResponseDtoDataItemMealsItemOptionsItemItemsItem } from './clientMenuListResponseDtoDataItemMealsItemOptionsItemItemsItem';

export type ClientMenuListResponseDtoDataItemMealsItemOptionsItem = {
  id: string;
  /** @nullable */
  name: string | null;
  orderIndex: number;
  items: ClientMenuListResponseDtoDataItemMealsItemOptionsItemItemsItem[];
};
