/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ClientMenuUpdateRequestDtoMealsToUpdateItemOptionsToAddItem } from './clientMenuUpdateRequestDtoMealsToUpdateItemOptionsToAddItem';
import type { ClientMenuUpdateRequestDtoMealsToUpdateItemOptionsToUpdateItem } from './clientMenuUpdateRequestDtoMealsToUpdateItemOptionsToUpdateItem';
import type { ClientMenuUpdateRequestDtoMealsToUpdateItemOptionsToDeleteItem } from './clientMenuUpdateRequestDtoMealsToUpdateItemOptionsToDeleteItem';

export type ClientMenuUpdateRequestDtoMealsToUpdateItem = {
  id: string;
  name?: string;
  /** @nullable */
  notes?: string | null;
  totalCalories?: number;
  /** @nullable */
  selectedOptionId?: string | null;
  optionsToAdd?: ClientMenuUpdateRequestDtoMealsToUpdateItemOptionsToAddItem[];
  optionsToUpdate?: ClientMenuUpdateRequestDtoMealsToUpdateItemOptionsToUpdateItem[];
  optionsToDelete?: ClientMenuUpdateRequestDtoMealsToUpdateItemOptionsToDeleteItem[];
};
