/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationResponseDtoDataChannel } from './conversationResponseDtoDataChannel';

export type ConversationResponseDtoData = {
  id: string;
  coachId: string;
  clientId: string;
  channel: ConversationResponseDtoDataChannel;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  lastMessageAt: string | null;
};
