/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationDtoChannel } from './conversationDtoChannel';

export interface ConversationDto {
  id: string;
  coachId: string;
  clientId: string;
  channel: ConversationDtoChannel;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  lastMessageAt: string | null;
}
