/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type ConversationResponseDtoDataChannel = typeof ConversationResponseDtoDataChannel[keyof typeof ConversationResponseDtoDataChannel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConversationResponseDtoDataChannel = {
  WHATSAPP: 'WHATSAPP',
  TELEGRAM: 'TELEGRAM',
  APP: 'APP',
} as const;
