/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { DailyStateResponseDtoDataWorkoutsItemEffortLevel } from './dailyStateResponseDtoDataWorkoutsItemEffortLevel';
import type { DailyStateResponseDtoDataWorkoutsItemExercisesItem } from './dailyStateResponseDtoDataWorkoutsItemExercisesItem';

export type DailyStateResponseDtoDataWorkoutsItem = {
  id: string;
  clientId: string;
  date: string;
  workoutType: string;
  effortLevel: DailyStateResponseDtoDataWorkoutsItemEffortLevel;
  /** @nullable */
  notes: string | null;
  loggedAt?: string;
  exercises: DailyStateResponseDtoDataWorkoutsItemExercisesItem[];
};
