/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type DailyStateResponseDtoDataDayType = typeof DailyStateResponseDtoDataDayType[keyof typeof DailyStateResponseDtoDataDayType] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DailyStateResponseDtoDataDayType = {
  TRAINING: 'TRAINING',
  REST: 'REST',
} as const;
