/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { DailyStateResponseDtoDataDayType } from './dailyStateResponseDtoDataDayType';
import type { DailyStateResponseDtoDataCalorieTargets } from './dailyStateResponseDtoDataCalorieTargets';
import type { DailyStateResponseDtoDataMealsItem } from './dailyStateResponseDtoDataMealsItem';
import type { DailyStateResponseDtoDataWorkoutsItem } from './dailyStateResponseDtoDataWorkoutsItem';
import type { DailyStateResponseDtoDataWeight } from './dailyStateResponseDtoDataWeight';
import type { DailyStateResponseDtoDataMetrics } from './dailyStateResponseDtoDataMetrics';

export type DailyStateResponseDtoData = {
  /** @nullable */
  dayType: DailyStateResponseDtoDataDayType;
  calorieTargets: DailyStateResponseDtoDataCalorieTargets;
  /** @nullable */
  activeCaloriesAllowed: number | null;
  consumedCalories: number;
  /** @nullable */
  remainingCalories: number | null;
  meals: DailyStateResponseDtoDataMealsItem[];
  workouts: DailyStateResponseDtoDataWorkoutsItem[];
  /** @nullable */
  weight: DailyStateResponseDtoDataWeight;
  /** @nullable */
  metrics: DailyStateResponseDtoDataMetrics;
};
