/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { DailyStateResponseDtoDataMetricsDate } from './dailyStateResponseDtoDataMetricsDate';
import type { DailyStateResponseDtoDataMetricsUpdatedAt } from './dailyStateResponseDtoDataMetricsUpdatedAt';

/**
 * @nullable
 */
export type DailyStateResponseDtoDataMetrics = {
  id: string;
  clientId: string;
  date: DailyStateResponseDtoDataMetricsDate;
  /** @nullable */
  steps: number | null;
  /** @nullable */
  waterLiters: number | null;
  /** @nullable */
  sleepHours: number | null;
  /** @nullable */
  notes: string | null;
  updatedAt: DailyStateResponseDtoDataMetricsUpdatedAt;
} | null;
