/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { DailyStateResponseDtoDataMealsItemDayType } from './dailyStateResponseDtoDataMealsItemDayType';

export type DailyStateResponseDtoDataMealsItem = {
  id: string;
  clientId: string;
  date: string;
  dayType: DailyStateResponseDtoDataMealsItemDayType;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  /** @nullable */
  description: string | null;
  /** @nullable */
  matchedMenuItemId: string | null;
  loggedAt?: string;
};
