/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type DailyStateResponseDtoDataWeight = {
  id: string;
  clientId: string;
  date: string;
  weightKg: number;
  /** @nullable */
  notes: string | null;
} | null;
