/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { DaySelectionResponseDtoDataDayType } from './daySelectionResponseDtoDataDayType';

export type DaySelectionResponseDtoData = {
  id: string;
  clientId: string;
  date: string;
  dayType: DaySelectionResponseDtoDataDayType;
  changedAt: string;
};
