/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type DaySelectionTodayResponseDtoDataDayType = typeof DaySelectionTodayResponseDtoDataDayType[keyof typeof DaySelectionTodayResponseDtoDataDayType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DaySelectionTodayResponseDtoDataDayType = {
  TRAINING: 'TRAINING',
  REST: 'REST',
} as const;
