/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type DaySelectionCreateRequestDtoDayType = typeof DaySelectionCreateRequestDtoDayType[keyof typeof DaySelectionCreateRequestDtoDayType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DaySelectionCreateRequestDtoDayType = {
  LOW: 'LOW',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  REST: 'REST',
} as const;
