/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { DaySelectionTodayResponseDtoDataDayType } from './daySelectionTodayResponseDtoDataDayType';

export type DaySelectionTodayResponseDtoData = {
  id: string;
  clientId: string;
  date: string;
  dayType: DaySelectionTodayResponseDtoDataDayType;
  changedAt: string;
};
