/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type ExerciseUpdateRequestDtoBodyType = typeof ExerciseUpdateRequestDtoBodyType[keyof typeof ExerciseUpdateRequestDtoBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExerciseUpdateRequestDtoBodyType = {
  ECTO: 'ECTO',
  ENDO: 'ENDO',
} as const;
