/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type ExerciseUpdateRequestDtoMuscleGroup = typeof ExerciseUpdateRequestDtoMuscleGroup[keyof typeof ExerciseUpdateRequestDtoMuscleGroup];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExerciseUpdateRequestDtoMuscleGroup = {
  CHEST: 'CHEST',
  BACK: 'BACK',
  SHOULDERS: 'SHOULDERS',
  LEGS: 'LEGS',
  GLUTES: 'GLUTES',
  ARMS: 'ARMS',
  BICEPS: 'BICEPS',
  TRICEPS: 'TRICEPS',
  ABS: 'ABS',
  FULL_BODY: 'FULL_BODY',
} as const;
