/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type ExerciseCreateRequestDtoWorkoutTypesItem = typeof ExerciseCreateRequestDtoWorkoutTypesItem[keyof typeof ExerciseCreateRequestDtoWorkoutTypesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExerciseCreateRequestDtoWorkoutTypesItem = {
  A: 'A',
  B: 'B',
  FBW: 'FBW',
  UPPER: 'UPPER',
  LOWER: 'LOWER',
  GLUTES: 'GLUTES',
  HIIT: 'HIIT',
  PUSH: 'PUSH',
  PULL: 'PULL',
  LEGS: 'LEGS',
} as const;
