/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type ExerciseCreateRequestDtoBodyType = typeof ExerciseCreateRequestDtoBodyType[keyof typeof ExerciseCreateRequestDtoBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExerciseCreateRequestDtoBodyType = {
  ECTO: 'ECTO',
  ENDO: 'ENDO',
} as const;
