/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type ExerciseUpdateRequestDtoGender = typeof ExerciseUpdateRequestDtoGender[keyof typeof ExerciseUpdateRequestDtoGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExerciseUpdateRequestDtoGender = {
  MALE: 'זכר',
  FEMALE: 'נקבה',
} as const;
