/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export interface FoodItemResponseDto {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  category: string;
  caloriesPer100g: number;
}
