/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export interface FoodItemRequestCreateDto {
  name: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  category?: string | null;
  /** @nullable */
  caloriesPer100g?: number | null;
  /** @nullable */
  proteinPer100g?: number | null;
}
