/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { MealTemplateResponseDto } from './mealTemplateResponseDto';

export type GetApiMealTemplatesId200 = {
  data?: MealTemplateResponseDto;
};
