/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiTrackingDailyStateRangeParams = {
/**
 * Start date (YYYY-MM-DD)
 */
startDate: string;
/**
 * End date (YYYY-MM-DD)
 */
endDate: string;
};
