/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { IncomingWebhookMessageDtoChannel } from './incomingWebhookMessageDtoChannel';
import type { IncomingWebhookMessageDtoContentType } from './incomingWebhookMessageDtoContentType';
import type { IncomingWebhookMessageDtoMedia } from './incomingWebhookMessageDtoMedia';

export interface IncomingWebhookMessageDto {
  fromPhone: string;
  toPhone: string;
  channel: IncomingWebhookMessageDtoChannel;
  contentType: IncomingWebhookMessageDtoContentType;
  text?: string;
  media?: IncomingWebhookMessageDtoMedia;
  sourceMessageId?: string;
}
