/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { LoginResponseDtoUser } from './loginResponseDtoUser';
import type { LoginResponseDtoTokens } from './loginResponseDtoTokens';

export interface LoginResponseDto {
  user: LoginResponseDtoUser;
  sessionId: string;
  tokens: LoginResponseDtoTokens;
}
