/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { LoginResponseDtoUserStatus } from './loginResponseDtoUserStatus';

export type LoginResponseDtoUser = {
  id: string;
  email: string;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  lastName: string | null;
  status: LoginResponseDtoUserStatus;
  role: string;
};
