/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type LoginResponseDtoUserStatus = typeof LoginResponseDtoUserStatus[keyof typeof LoginResponseDtoUserStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginResponseDtoUserStatus = {
  active: 'active',
  locked: 'locked',
} as const;
