/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { MealLogResponseDtoData } from './mealLogResponseDtoData';

export interface MealLogResponseDto {
  data: MealLogResponseDtoData;
}
