/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { MealTemplateResponseDtoItemsItem } from './mealTemplateResponseDtoItemsItem';

export interface MealTemplateResponseDto {
  id: string;
  name: string;
  kind: string;
  totalCalories: number;
  items: MealTemplateResponseDtoItemsItem[];
}
