/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { MealTemplateResponseDtoItemsItemFoodItem } from './mealTemplateResponseDtoItemsItemFoodItem';

export type MealTemplateResponseDtoItemsItem = {
  id: string;
  foodItemId: string;
  role: string;
  grams: number;
  foodItem: MealTemplateResponseDtoItemsItemFoodItem;
};
