/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type MealLogHistoryResponseDtoDataItemDayType = typeof MealLogHistoryResponseDtoDataItemDayType[keyof typeof MealLogHistoryResponseDtoDataItemDayType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MealLogHistoryResponseDtoDataItemDayType = {
  LOW: 'LOW',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  REST: 'REST',
} as const;
