/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { MealLogCreateRequestDtoDayType } from './mealLogCreateRequestDtoDayType';

export interface MealLogCreateRequestDto {
  date?: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  description?: string;
  matchedMenuItemId?: string;
  dayType: MealLogCreateRequestDtoDayType;
}
