/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type MealTemplateCreateRequestDtoItemsItem = {
  foodItemId: string;
  role: string;
  defaultGrams?: number;
  /** @nullable */
  defaultCalories?: number | null;
  /** @nullable */
  notes?: string | null;
};
