/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export interface MediaInputDto {
  mediaUrl: string;
  mediaMimeType?: string;
  mediaDurationSec?: number;
  mediaThumbnail?: string;
}
