/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { MessageListResponseDtoDataItemSender } from './messageListResponseDtoDataItemSender';
import type { MessageListResponseDtoDataItemContentType } from './messageListResponseDtoDataItemContentType';
import type { MessageListResponseDtoDataItemAiDecision } from './messageListResponseDtoDataItemAiDecision';
import type { MessageListResponseDtoDataItemHandledBy } from './messageListResponseDtoDataItemHandledBy';

export type MessageListResponseDtoDataItem = {
  id: string;
  conversationId: string;
  sender: MessageListResponseDtoDataItemSender;
  contentType: MessageListResponseDtoDataItemContentType;
  /** @nullable */
  text: string | null;
  /** @nullable */
  mediaUrl: string | null;
  /** @nullable */
  mediaMimeType: string | null;
  /** @nullable */
  mediaDurationSec: number | null;
  /** @nullable */
  mediaThumbnail: string | null;
  /** @nullable */
  sourceMessageId?: string | null;
  /** @nullable */
  autoGenerated?: boolean | null;
  /** @nullable */
  aiDecision: MessageListResponseDtoDataItemAiDecision;
  /** @nullable */
  aiSuggestedReply: string | null;
  /** @nullable */
  handledAt: string | null;
  /** @nullable */
  handledBy: MessageListResponseDtoDataItemHandledBy;
  createdAt: string;
  updatedAt?: string;
};
