/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type MessageDtoContentType = typeof MessageDtoContentType[keyof typeof MessageDtoContentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageDtoContentType = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  AUDIO: 'AUDIO',
  VIDEO: 'VIDEO',
} as const;
