/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type MessageResponseDtoDataAiDecision = typeof MessageResponseDtoDataAiDecision[keyof typeof MessageResponseDtoDataAiDecision] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageResponseDtoDataAiDecision = {
  AUTO_REPLY: 'AUTO_REPLY',
  COACH_REPLY: 'COACH_REPLY',
} as const;
