/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type MessageHandledByEnum = typeof MessageHandledByEnum[keyof typeof MessageHandledByEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageHandledByEnum = {
  AI: 'AI',
  COACH: 'COACH',
} as const;
