/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type MessageResponseDtoDataSender = typeof MessageResponseDtoDataSender[keyof typeof MessageResponseDtoDataSender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageResponseDtoDataSender = {
  CLIENT: 'CLIENT',
  COACH: 'COACH',
  AI: 'AI',
} as const;
