/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { MessageResponseDtoDataSender } from './messageResponseDtoDataSender';
import type { MessageResponseDtoDataContentType } from './messageResponseDtoDataContentType';
import type { MessageResponseDtoDataAiDecision } from './messageResponseDtoDataAiDecision';
import type { MessageResponseDtoDataHandledBy } from './messageResponseDtoDataHandledBy';

export type MessageResponseDtoData = {
  id: string;
  conversationId: string;
  sender: MessageResponseDtoDataSender;
  contentType: MessageResponseDtoDataContentType;
  /** @nullable */
  text: string | null;
  /** @nullable */
  mediaUrl: string | null;
  /** @nullable */
  mediaMimeType: string | null;
  /** @nullable */
  mediaDurationSec: number | null;
  /** @nullable */
  mediaThumbnail: string | null;
  /** @nullable */
  sourceMessageId?: string | null;
  /** @nullable */
  autoGenerated?: boolean | null;
  /** @nullable */
  aiDecision: MessageResponseDtoDataAiDecision;
  /** @nullable */
  aiSuggestedReply: string | null;
  /** @nullable */
  handledAt: string | null;
  /** @nullable */
  handledBy: MessageResponseDtoDataHandledBy;
  createdAt: string;
  updatedAt?: string;
};
