/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { MessageDtoSender } from './messageDtoSender';
import type { MessageDtoContentType } from './messageDtoContentType';
import type { MessageDtoAiDecision } from './messageDtoAiDecision';
import type { MessageDtoHandledBy } from './messageDtoHandledBy';

export interface MessageDto {
  id: string;
  conversationId: string;
  sender: MessageDtoSender;
  contentType: MessageDtoContentType;
  /** @nullable */
  text: string | null;
  /** @nullable */
  mediaUrl: string | null;
  /** @nullable */
  mediaMimeType: string | null;
  /** @nullable */
  mediaDurationSec: number | null;
  /** @nullable */
  mediaThumbnail: string | null;
  /** @nullable */
  sourceMessageId?: string | null;
  /** @nullable */
  autoGenerated?: boolean | null;
  /** @nullable */
  aiDecision: MessageDtoAiDecision;
  /** @nullable */
  aiSuggestedReply: string | null;
  /** @nullable */
  handledAt: string | null;
  /** @nullable */
  handledBy: MessageDtoHandledBy;
  createdAt: string;
  updatedAt?: string;
}
