/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type MessageDtoAiDecision = typeof MessageDtoAiDecision[keyof typeof MessageDtoAiDecision] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageDtoAiDecision = {
  AUTO_REPLY: 'AUTO_REPLY',
  COACH_REPLY: 'COACH_REPLY',
} as const;
