/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type MessageResponseDtoDataHandledBy = typeof MessageResponseDtoDataHandledBy[keyof typeof MessageResponseDtoDataHandledBy] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageResponseDtoDataHandledBy = {
  AI: 'AI',
  COACH: 'COACH',
} as const;
