/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { MetricsLogResponseDtoDate } from './metricsLogResponseDtoDate';
import type { MetricsLogResponseDtoUpdatedAt } from './metricsLogResponseDtoUpdatedAt';

export interface MetricsLogResponseDto {
  id: string;
  clientId: string;
  date: MetricsLogResponseDtoDate;
  /** @nullable */
  steps: number | null;
  /** @nullable */
  waterLiters: number | null;
  /** @nullable */
  sleepHours: number | null;
  /** @nullable */
  notes: string | null;
  updatedAt: MetricsLogResponseDtoUpdatedAt;
}
