/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type MuscleGroupEnum = typeof MuscleGroupEnum[keyof typeof MuscleGroupEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MuscleGroupEnum = {
  CHEST: 'חזה',
  BACK: 'גב',
  SHOULDERS: 'כתפיים',
  LEGS: 'רגליים',
  GLUTES: 'ישבן',
  ARMS: 'ידיים',
  BICEPS: 'יד קדמית',
  TRICEPS: 'יד אחורית',
  ABS: 'בטן',
  FULL_BODY: 'גוף מלא',
} as const;
