/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { PendingClientMessageResponseDtoDataItemSender } from './pendingClientMessageResponseDtoDataItemSender';
import type { PendingClientMessageResponseDtoDataItemContentType } from './pendingClientMessageResponseDtoDataItemContentType';
import type { PendingClientMessageResponseDtoDataItemAiDecision } from './pendingClientMessageResponseDtoDataItemAiDecision';
import type { PendingClientMessageResponseDtoDataItemHandledBy } from './pendingClientMessageResponseDtoDataItemHandledBy';

export type PendingClientMessageResponseDtoDataItem = {
  id: string;
  conversationId: string;
  sender: PendingClientMessageResponseDtoDataItemSender;
  contentType: PendingClientMessageResponseDtoDataItemContentType;
  /** @nullable */
  text: string | null;
  /** @nullable */
  mediaUrl: string | null;
  /** @nullable */
  mediaMimeType: string | null;
  /** @nullable */
  mediaDurationSec: number | null;
  /** @nullable */
  mediaThumbnail: string | null;
  /** @nullable */
  sourceMessageId?: string | null;
  /** @nullable */
  autoGenerated?: boolean | null;
  /** @nullable */
  aiDecision: PendingClientMessageResponseDtoDataItemAiDecision;
  /** @nullable */
  aiSuggestedReply: string | null;
  /** @nullable */
  handledAt: string | null;
  /** @nullable */
  handledBy: PendingClientMessageResponseDtoDataItemHandledBy;
  createdAt: string;
  updatedAt?: string;
};
