/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterResponseDtoDataId } from './registerResponseDtoDataId';

export type RegisterResponseDtoData = {
  message: string;
  id: RegisterResponseDtoDataId;
};
