/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type RegisterRequestDtoRole = typeof RegisterRequestDtoRole[keyof typeof RegisterRequestDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterRequestDtoRole = {
  trainer: 'trainer',
  client: 'client',
  admin: 'admin',
} as const;
