/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { SendCoachMessageRequestDtoContentType } from './sendCoachMessageRequestDtoContentType';
import type { SendCoachMessageRequestDtoMedia } from './sendCoachMessageRequestDtoMedia';

export interface SendCoachMessageRequestDto {
  contentType: SendCoachMessageRequestDtoContentType;
  text?: string;
  media?: SendCoachMessageRequestDtoMedia;
}
