/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateMenuResponseDtoMealsItem } from './templateMenuResponseDtoMealsItem';
import type { TemplateMenuResponseDtoVitaminsItem } from './templateMenuResponseDtoVitaminsItem';

export interface TemplateMenuResponseDto {
  id: string;
  coachId: string;
  name: string;
  dayType: string;
  /** @nullable */
  notes: string | null;
  totalCalories: number;
  meals: TemplateMenuResponseDtoMealsItem[];
  vitamins: TemplateMenuResponseDtoVitaminsItem[];
}
