/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateMenuUpdateRequestDtoMealOptionsToAddItemTemplateItemsItem } from './templateMenuUpdateRequestDtoMealOptionsToAddItemTemplateItemsItem';

export type TemplateMenuUpdateRequestDtoMealOptionsToAddItemTemplate = {
  name: string;
  kind?: string;
  items?: TemplateMenuUpdateRequestDtoMealOptionsToAddItemTemplateItemsItem[];
};
