/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateMenuUpdateRequestDtoMealsToAddItemOptionsItem } from './templateMenuUpdateRequestDtoMealsToAddItemOptionsItem';

export type TemplateMenuUpdateRequestDtoMealsToAddItem = {
  name: string;
  /** @nullable */
  notes?: string | null;
  totalCalories?: number;
  options?: TemplateMenuUpdateRequestDtoMealsToAddItemOptionsItem[];
};
