/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export interface UpsertUserInfoRequestDto {
  dateOfBirth?: string;
  gender?: string;
  address?: string;
  city?: string;
  profileImageUrl?: string;
  height?: number;
  age?: number;
}
