/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type UpsertUserInfoResponseDtoStatus = typeof UpsertUserInfoResponseDtoStatus[keyof typeof UpsertUserInfoResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpsertUserInfoResponseDtoStatus = {
  active: 'active',
  deleted: 'deleted',
  archived: 'archived',
} as const;
