/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type UserResponseDtoStatus = typeof UserResponseDtoStatus[keyof typeof UserResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseDtoStatus = {
  active: 'active',
  deleted: 'deleted',
  locked: 'locked',
} as const;
