/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseDtoStatus } from './userResponseDtoStatus';
import type { UserResponseDtoRole } from './userResponseDtoRole';

export interface UserResponseDto {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  phone?: string;
  status: UserResponseDtoStatus;
  role: UserResponseDtoRole;
  createdAt: string;
  updatedAt: string;
}
