/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type UserInfoResponseDtoStatus = typeof UserInfoResponseDtoStatus[keyof typeof UserInfoResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserInfoResponseDtoStatus = {
  active: 'active',
  deleted: 'deleted',
  archived: 'archived',
} as const;
