/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { WeightHistoryResponseDtoDataItem } from './weightHistoryResponseDtoDataItem';

export interface WeightHistoryResponseDto {
  data: WeightHistoryResponseDtoDataItem[];
}
