/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type WorkoutProgramUpdateRequestDtoExercisesToUpdateItem = {
  id: string;
  exerciseId?: string;
  sets?: number;
  reps?: string;
  /** @nullable */
  weight?: number | null;
  /** @nullable */
  rest?: number | null;
  order?: number;
  /** @nullable */
  notes?: string | null;
};
