/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkoutProgramUpdateRequestDtoExercisesToAddItem } from './workoutProgramUpdateRequestDtoExercisesToAddItem';
import type { WorkoutProgramUpdateRequestDtoExercisesToUpdateItem } from './workoutProgramUpdateRequestDtoExercisesToUpdateItem';
import type { WorkoutProgramUpdateRequestDtoExercisesToDeleteItem } from './workoutProgramUpdateRequestDtoExercisesToDeleteItem';

export interface WorkoutProgramUpdateRequestDto {
  name?: string;
  exercisesToAdd?: WorkoutProgramUpdateRequestDtoExercisesToAddItem[];
  exercisesToUpdate?: WorkoutProgramUpdateRequestDtoExercisesToUpdateItem[];
  exercisesToDelete?: WorkoutProgramUpdateRequestDtoExercisesToDeleteItem[];
}
