/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkoutTemplateResponseDtoGender } from './workoutTemplateResponseDtoGender';
import type { WorkoutTemplateResponseDtoBodyType } from './workoutTemplateResponseDtoBodyType';

export interface WorkoutTemplateResponseDto {
  id: string;
  gender: WorkoutTemplateResponseDtoGender;
  level: number;
  /** @nullable */
  bodyType: WorkoutTemplateResponseDtoBodyType;
  workoutType: string;
  muscleGroups: string[];
  /** @nullable */
  name: string | null;
  /** @nullable */
  notes: string | null;
}
