/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkoutLogUpdateRequestDtoEffortLevel } from './workoutLogUpdateRequestDtoEffortLevel';
import type { WorkoutLogUpdateRequestDtoExercisesItem } from './workoutLogUpdateRequestDtoExercisesItem';

export interface WorkoutLogUpdateRequestDto {
  workoutType?: string;
  effortLevel?: WorkoutLogUpdateRequestDtoEffortLevel;
  notes?: string;
  exercises?: WorkoutLogUpdateRequestDtoExercisesItem[];
}
