/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkoutLogResponseDtoDataEffortLevel } from './workoutLogResponseDtoDataEffortLevel';
import type { WorkoutLogResponseDtoDataExercisesItem } from './workoutLogResponseDtoDataExercisesItem';

export type WorkoutLogResponseDtoData = {
  id: string;
  clientId: string;
  date: string;
  workoutType: string;
  effortLevel: WorkoutLogResponseDtoDataEffortLevel;
  /** @nullable */
  notes: string | null;
  loggedAt?: string;
  exercises: WorkoutLogResponseDtoDataExercisesItem[];
};
