/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkoutTemplateUpdateRequestDtoGender } from './workoutTemplateUpdateRequestDtoGender';
import type { WorkoutTemplateUpdateRequestDtoBodyType } from './workoutTemplateUpdateRequestDtoBodyType';

export interface WorkoutTemplateUpdateRequestDto {
  gender?: WorkoutTemplateUpdateRequestDtoGender;
  level?: number;
  /** @nullable */
  bodyType?: WorkoutTemplateUpdateRequestDtoBodyType;
  workoutType?: string;
  muscleGroups?: string[];
  /** @nullable */
  name?: string | null;
  /** @nullable */
  notes?: string | null;
}
