/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type WorkoutTemplateResponseDtoBodyType = typeof WorkoutTemplateResponseDtoBodyType[keyof typeof WorkoutTemplateResponseDtoBodyType] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkoutTemplateResponseDtoBodyType = {
  ECTO: 'ECTO',
  ENDO: 'ENDO',
} as const;
