/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkoutLogHistoryResponseDtoDataItemEffortLevel } from './workoutLogHistoryResponseDtoDataItemEffortLevel';
import type { WorkoutLogHistoryResponseDtoDataItemExercisesItem } from './workoutLogHistoryResponseDtoDataItemExercisesItem';

export type WorkoutLogHistoryResponseDtoDataItem = {
  id: string;
  clientId: string;
  date: string;
  workoutType: string;
  effortLevel: WorkoutLogHistoryResponseDtoDataItemEffortLevel;
  /** @nullable */
  notes: string | null;
  loggedAt?: string;
  exercises: WorkoutLogHistoryResponseDtoDataItemExercisesItem[];
};
