/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkoutProgramResponseDtoExercisesItem } from './workoutProgramResponseDtoExercisesItem';

export interface WorkoutProgramResponseDto {
  id: string;
  name: string;
  clientId: string;
  coachId: string;
  /** @nullable */
  templateId?: string | null;
  createdAt: string;
  updatedAt: string;
  exercises: WorkoutProgramResponseDtoExercisesItem[];
}
