/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type WorkoutLogResponseDtoDataEffortLevel = typeof WorkoutLogResponseDtoDataEffortLevel[keyof typeof WorkoutLogResponseDtoDataEffortLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkoutLogResponseDtoDataEffortLevel = {
  EASY: 'EASY',
  NORMAL: 'NORMAL',
  HARD: 'HARD',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED',
} as const;
