/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkoutLogCreateRequestDtoEffortLevel } from './workoutLogCreateRequestDtoEffortLevel';
import type { WorkoutLogCreateRequestDtoExercisesItem } from './workoutLogCreateRequestDtoExercisesItem';

export interface WorkoutLogCreateRequestDto {
  date?: string;
  workoutType: string;
  effortLevel: WorkoutLogCreateRequestDtoEffortLevel;
  notes?: string;
  exercises: WorkoutLogCreateRequestDtoExercisesItem[];
}
