/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkoutProgramResponseDtoExercisesItemExercise } from './workoutProgramResponseDtoExercisesItemExercise';

export type WorkoutProgramResponseDtoExercisesItem = {
  id: string;
  programId: string;
  exerciseId: string;
  sets: number;
  reps: string;
  /** @nullable */
  weight: number | null;
  /** @nullable */
  rest: number | null;
  order: number;
  /** @nullable */
  notes: string | null;
  createdAt: string;
  updatedAt: string;
  exercise: WorkoutProgramResponseDtoExercisesItemExercise;
};
