/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

export type WorkoutTemplateUpdateRequestDtoGender = typeof WorkoutTemplateUpdateRequestDtoGender[keyof typeof WorkoutTemplateUpdateRequestDtoGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkoutTemplateUpdateRequestDtoGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;
