/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkoutProgramCreateRequestDtoExercises } from './workoutProgramCreateRequestDtoExercises';

export interface WorkoutProgramCreateRequestDto {
  name: string;
  clientId: string;
  coachId: string;
  templateId?: string;
  exercises: WorkoutProgramCreateRequestDtoExercises;
}
