/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Nutri-App Gateway API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type WorkoutTemplateCreateRequestDtoBodyType = typeof WorkoutTemplateCreateRequestDtoBodyType[keyof typeof WorkoutTemplateCreateRequestDtoBodyType] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkoutTemplateCreateRequestDtoBodyType = {
  ECTO: 'ECTO',
  ENDO: 'ENDO',
} as const;
