/* prisma/seed.js */

const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const COACH_ID = "5ed57b28-caf4-4f78-bba5-bce43996ddfc";

const clients = [
  "04658b3c-c687-4899-a334-2ab4055120c2", // client1 - משה מזרחי
  "4477eeaf-284a-40b4-939f-e95646aa2b04", // client2 - יעל לוי
  "3ee5b30d-3b6a-41ed-a88b-7383edcc20ac", // client3 - יואב וולף
  "7c757600-4d8f-410a-95e6-a5b22101cabd", // client4 - לינוי שטרן
  "9c3499fa-e9ee-4b62-bd89-e725f507b3e5", // client5 - ניצן פרץ
  "c3b9cd00-fd91-488c-bd2a-2c1d97a96242", // client6 - מאיה חדד
  "61a0703b-f007-48a9-bda0-f45c779a03ad", // client7 - מאיה חדד
  "0f0b273c-8f48-4dfc-8529-744639ec22b7", // client8 - נועה כהן
  "0669dc24-2630-4a15-94d7-19e42dbf1ece", // client9 - עדן ביטון
  "1d2236eb-594b-404a-98e4-2ee94da9590c", // client10 - אליעד לוי
  "21dbdb35-7f93-4441-90cf-ca2e7ecdfc79", // client11 - אליעד ברוך
  "7afdc547-5022-4d85-b015-43345645dd7d", // client12 - עדן ביטון
  "85512046-96fd-4e85-8a78-c840fa6cfe23", // client13 - נועה אלבז
  "37ede9a1-c2f9-4ff2-8ae8-2391a4b2fff2", // client14 - תומר אלבז
  "4574b2b9-37ba-480b-ae38-7da9b049312b", // client15 - שון וולף
  "1dc5d2ac-f772-462d-9392-acb7936b2fe9", // client16 - מאיה מזרחי
  "cd77d1eb-ebe0-45cf-84dd-5c41785bd9ea", // client17 - משה וולף
  "701587c5-63bc-4a0c-a15e-d218b0fd9e11", // client18 - דוד חדד
  "30975a16-001e-437c-bb69-e8dbd8ff8870", // client19 - מאיה אלבז
  "24e27b82-ca8c-4264-9568-15bc4a57d399", // client20 - שקד אלבז
];


const randomChannel = "TELEGRAM";

async function seed() {
  console.log("🌱 Seeding conversations & messages...");

  await prisma.message.deleteMany();
  await prisma.conversation.deleteMany();

  for (let i = 0; i < clients.length; i++) {
    const clientId = clients[i];

    const conversation = await prisma.conversation.create({
      data: {
        coachId: COACH_ID,
        clientId,
        channel: randomChannel,
      },
    });

    // הודעת CLIENT
    const clientMessage = await prisma.message.create({
      data: {
        conversationId: conversation.id,
        sender: "CLIENT",
        contentType: "TEXT",
        text: "היי, היה לי קשה לעמוד בתפריט היום 😕",
        createdAt: new Date(Date.now() - 1000 * 60 * 5),
      },
    });

    // חצי AUTO_REPLY, חצי SUGGEST
    const isAutoReply = i % 2 === 0;

    if (isAutoReply) {
      // AI AUTO REPLY
      const aiReply = await prisma.message.create({
        data: {
          conversationId: conversation.id,
          sender: "AI",
          contentType: "TEXT",
          text: "זה קורה, גם ימים כאלה הם חלק מהתהליך 💪 מחר חוזרים למסלול.",
          autoGenerated: true,
        },
      });

      await prisma.message.update({
        where: { id: clientMessage.id },
        data: {
          aiDecision: "AUTO_REPLY",
          handledBy: "AI",
          handledAt: new Date(),
        },
      });

      await prisma.conversation.update({
        where: { id: conversation.id },
        data: {
          lastMessageAt: aiReply.createdAt,
        },
      });
    } else {
      // AI SUGGESTION ONLY
      await prisma.message.update({
        where: { id: clientMessage.id },
        data: {
          aiDecision: "COACH_REPLY",
          aiSuggestedReply:
            "זה לגמרי מובן. בוא ננסה להבין יחד מה הקשה עליך היום ואיך אפשר להקל מחר.",
        },
      });

      await prisma.conversation.update({
        where: { id: conversation.id },
        data: {
          lastMessageAt: clientMessage.createdAt,
        },
      });
    }
  }

  console.log("✅ Seed completed successfully");
}

seed()
  .catch((e) => {
    console.error("❌ Seed failed", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
