/* prisma/seed.js */

const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const COACH_ID = "bae20c85-f3b3-44e8-a001-1d236347665d";

const clients = [
  "5f4e6f52-8362-42d4-99e2-a3ff36296ddf", // אור ברוך
  "820c12f3-e49c-4b1d-b1ac-7dec62b02fd6", // נועה חדד
  "748a76d4-acd3-44f7-94b1-91ce0b0e3ffd", // אור לוי
  "e69ab580-ae45-485a-965d-c54d8c7bb34e", // מאיה מזרחי
  "2d2ac147-7a2d-4c0f-a655-89d3d9498082", // רוני פרץ
  "92f874da-cd65-4648-800b-bab55a3c6561", // יוסי אלבז
  "5afef180-5baf-4dce-b2b4-51097db344a5", // שון חדד
  "8ac90701-8220-441a-ac6f-49effd171846", // אליעד וולף
  "78d0b192-7579-4cf4-a625-fe6ebd4f5952", // דניאל מזרחי
  "82d47527-4e9d-4d46-8746-c7f52787b053", // יואב ברוך
  "a701dd31-04b9-478a-b926-f731e253d4e0", // תומר כהן
  "d1e38e8b-6b23-4dc2-a1bf-aa199ea136e5", // לינוי ברוך
  "dc868bad-9822-487f-99d7-1af4ea95ff33", // תומר פרץ
  "5b39f47e-df9d-459d-965f-c169ac7f11aa", // מאיה מזרחי
  "81d3ac72-2d04-412e-a6f8-5a641807f6db", // שיר ביטון
  "cc4c4b83-2541-40f5-858e-e3f6ca7e2676", // ניצן כהן
  "73e5f55e-fbcc-4073-8488-bb8af199953e", // יואב מזרחי
  "a1930ec4-0f29-49ce-965d-4521e4ca83a4", // יוסי חדד
  "c148d51a-9910-4c10-94c6-7fc5bd662e2d", // ניצן מלול
  "9175d0c6-0abe-4782-bbce-d3dbcb6eff70", // יעל כהן
];


const randomChannel = "TELEGRAM";

async function seed() {
  console.log("🌱 Seeding conversations & messages...");

  await prisma.message.deleteMany();
  await prisma.conversation.deleteMany();

  for (let i = 0; i < clients.length; i++) {
    const clientId = clients[i];

    const conversation = await prisma.conversation.create({
      data: {
        coachId: COACH_ID,
        clientId,
        channel: randomChannel,
      },
    });

    // הודעת CLIENT
    const clientMessage = await prisma.message.create({
      data: {
        conversationId: conversation.id,
        sender: "CLIENT",
        contentType: "TEXT",
        text: "היי, היה לי קשה לעמוד בתפריט היום 😕",
        createdAt: new Date(Date.now() - 1000 * 60 * 5),
      },
    });

    // חצי AUTO_REPLY, חצי SUGGEST
    const isAutoReply = i % 2 === 0;

    if (isAutoReply) {
      // AI AUTO REPLY
      const aiReply = await prisma.message.create({
        data: {
          conversationId: conversation.id,
          sender: "AI",
          contentType: "TEXT",
          text: "זה קורה, גם ימים כאלה הם חלק מהתהליך 💪 מחר חוזרים למסלול.",
          autoGenerated: true,
        },
      });

      await prisma.message.update({
        where: { id: clientMessage.id },
        data: {
          aiDecision: "AUTO_REPLY",
          handledBy: "AI",
          handledAt: new Date(),
        },
      });

      await prisma.conversation.update({
        where: { id: conversation.id },
        data: {
          lastMessageAt: aiReply.createdAt,
        },
      });
    } else {
      // AI SUGGESTION ONLY
      await prisma.message.update({
        where: { id: clientMessage.id },
        data: {
          aiDecision: "COACH_REPLY",
          aiSuggestedReply:
            "זה לגמרי מובן. בוא ננסה להבין יחד מה הקשה עליך היום ואיך אפשר להקל מחר.",
        },
      });

      await prisma.conversation.update({
        where: { id: conversation.id },
        data: {
          lastMessageAt: clientMessage.createdAt,
        },
      });
    }
  }

  console.log("✅ Seed completed successfully");
}

seed()
  .catch((e) => {
    console.error("❌ Seed failed", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
