/* prisma/seed.js */

const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const COACH_ID = "ba59ccee-bd43-4102-acb8-fd11184c2bad";

const clients = [
  "80d90a32-1bd0-407b-b4b6-400463dc341a",
  "db803c75-7b4e-4c95-8b15-f59445e5632f",
  "b9483c1f-f4f9-4cab-bbb9-100184053e70",
  "64ab6529-94dd-4bd1-8554-eb19f9edec90",
  "46eb16f4-a9d7-4c55-9bf6-bcd54f9a578e",
  "dc9e3a95-4efa-43eb-891d-c8cdc45a3c60",
];

const randomChannel = "TELEGRAM";

async function seed() {
  console.log("🌱 Seeding conversations & messages...");

  await prisma.message.deleteMany();
  await prisma.conversation.deleteMany();

  for (let i = 0; i < clients.length; i++) {
    const clientId = clients[i];

    const conversation = await prisma.conversation.create({
      data: {
        coachId: COACH_ID,
        clientId,
        channel: randomChannel,
      },
    });

    // הודעת CLIENT
    const clientMessage = await prisma.message.create({
      data: {
        conversationId: conversation.id,
        sender: "CLIENT",
        contentType: "TEXT",
        text: "היי, היה לי קשה לעמוד בתפריט היום 😕",
        createdAt: new Date(Date.now() - 1000 * 60 * 5),
      },
    });

    // חצי AUTO_REPLY, חצי SUGGEST
    const isAutoReply = i % 2 === 0;

    if (isAutoReply) {
      // AI AUTO REPLY
      const aiReply = await prisma.message.create({
        data: {
          conversationId: conversation.id,
          sender: "AI",
          contentType: "TEXT",
          text: "זה קורה, גם ימים כאלה הם חלק מהתהליך 💪 מחר חוזרים למסלול.",
          autoGenerated: true,
        },
      });

      await prisma.message.update({
        where: { id: clientMessage.id },
        data: {
          aiDecision: "AUTO_REPLY",
          handledBy: "AI",
          handledAt: new Date(),
        },
      });

      await prisma.conversation.update({
        where: { id: conversation.id },
        data: {
          lastMessageAt: aiReply.createdAt,
        },
      });
    } else {
      // AI SUGGESTION ONLY
      await prisma.message.update({
        where: { id: clientMessage.id },
        data: {
          aiDecision: "COACH_REPLY",
          aiSuggestedReply:
            "זה לגמרי מובן. בוא ננסה להבין יחד מה הקשה עליך היום ואיך אפשר להקל מחר.",
        },
      });

      await prisma.conversation.update({
        where: { id: conversation.id },
        data: {
          lastMessageAt: clientMessage.createdAt,
        },
      });
    }
  }

  console.log("✅ Seed completed successfully");
}

seed()
  .catch((e) => {
    console.error("❌ Seed failed", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
