// src/dtos/message.dto.js
const { z } = require("zod");

const MessageContentTypeEnum = z.enum([
  "TEXT",
  "IMAGE",
  "AUDIO",
  "VIDEO",
]);


const MediaDto = z.object({
  mediaUrl: z.string().url().optional(),
  mediaMimeType: z.string().optional(),
  mediaDurationSec: z.number().int().optional(),
  mediaThumbnail: z.string().optional(),
});

const CreateClientMessageDto = z.object({
  conversationId: z.string().min(1),
  contentType: MessageContentTypeEnum,
  text: z.string().optional(),
  media: MediaDto.optional(),
  sourceMessageId: z.string().optional(),
}).superRefine((value, ctx) => {
  if (value.contentType !== "TEXT" && !value.media?.mediaUrl) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ["media", "mediaUrl"],
      message: "media.mediaUrl is required for non-TEXT messages",
    });
  }
});

const CreateCoachMessageDto = z.object({
  conversationId: z.string().min(1),
  contentType: MessageContentTypeEnum,
  text: z.string().optional(),
  media: MediaDto.optional(),
}).superRefine((value, ctx) => {
  if (value.contentType !== "TEXT" && !value.media?.mediaUrl) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ["media", "mediaUrl"],
      message: "media.mediaUrl is required for non-TEXT coach messages",
    });
  }
});

const CreateAiMessageDto = z.object({
  conversationId: z.string().min(1),
  text: z.string().min(1),
  autoGenerated: z.boolean().optional(),
});

const MarkClientMessageHandledDto = z.object({
  handledBy: z.enum(["AI", "COACH"]),
});

const GetMessagesByConversationDto = z.object({
  conversationId: z.string().min(1),
});

module.exports = {
  CreateClientMessageDto,
  CreateCoachMessageDto,
  CreateAiMessageDto,
  MarkClientMessageHandledDto,
  GetMessagesByConversationDto,
};
