-- CreateEnum
CREATE TYPE "MessageSender" AS ENUM ('CLIENT', 'COACH', 'AI');

-- CreateEnum
CREATE TYPE "AIDecision" AS ENUM ('AUTO_REPLY', 'COACH_REPLY');

-- CreateEnum
CREATE TYPE "MessageHandledBy" AS ENUM ('AI', 'COACH');

-- CreateEnum
CREATE TYPE "ConversationChannel" AS ENUM ('WHATSAPP', 'TELEGRAM', 'APP');

-- CreateEnum
CREATE TYPE "MessageContentType" AS ENUM ('TEXT', 'IMAGE', 'AUDIO', 'VIDEO');

-- CreateTable
CREATE TABLE "Conversation" (
    "id" TEXT NOT NULL,
    "coachId" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "channel" "ConversationChannel" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "lastMessageAt" TIMESTAMP(3),

    CONSTRAINT "Conversation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Message" (
    "id" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "sender" "MessageSender" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "contentType" "MessageContentType" NOT NULL,
    "text" TEXT,
    "mediaUrl" TEXT,
    "mediaMimeType" TEXT,
    "mediaDurationSec" INTEGER,
    "mediaThumbnail" TEXT,
    "aiDecision" "AIDecision",
    "aiSuggestedReply" TEXT,
    "handledAt" TIMESTAMP(3),
    "handledBy" "MessageHandledBy",
    "sourceMessageId" TEXT,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "Message_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Conversation_coachId_idx" ON "Conversation"("coachId");

-- CreateIndex
CREATE INDEX "Conversation_clientId_idx" ON "Conversation"("clientId");

-- CreateIndex
CREATE UNIQUE INDEX "Conversation_coachId_clientId_channel_key" ON "Conversation"("coachId", "clientId", "channel");

-- CreateIndex
CREATE INDEX "Message_conversationId_idx" ON "Message"("conversationId");

-- CreateIndex
CREATE INDEX "Message_sender_idx" ON "Message"("sender");

-- CreateIndex
CREATE INDEX "Message_handledAt_idx" ON "Message"("handledAt");

-- CreateIndex
CREATE INDEX "Message_aiDecision_idx" ON "Message"("aiDecision");

-- CreateIndex
CREATE INDEX "Message_contentType_idx" ON "Message"("contentType");

-- AddForeignKey
ALTER TABLE "Message" ADD CONSTRAINT "Message_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
