/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/clients/ClientCard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clients)'}/ClientsScreen` | `/ClientsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clients)'}/[id]` | `/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/clients/FilterBar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(analytics)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(chat)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clients)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(plans)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/clients/ClientCard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(clients)'}/ClientsScreen` | `/ClientsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(clients)'}/[id]` | `/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/clients/FilterBar`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(analytics)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(chat)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(clients)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(plans)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../src/components/clients/ClientCard${`?${string}` | `#${string}` | ''}` | `${'/(clients)'}/ClientsScreen${`?${string}` | `#${string}` | ''}` | `/ClientsScreen${`?${string}` | `#${string}` | ''}` | `${'/(clients)'}/[id]${`?${string}` | `#${string}` | ''}` | `/[id]${`?${string}` | `#${string}` | ''}` | `/../src/components/clients/FilterBar${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(analytics)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(chat)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(clients)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(plans)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/clients/ClientCard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clients)'}/ClientsScreen` | `/ClientsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clients)'}/[id]` | `/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/clients/FilterBar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(analytics)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(chat)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clients)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(plans)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
