import { StyleSheet } from "react-native";
import { colors } from "src/styles/colors";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.white,
    padding: 18,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.neutral200,
    marginBottom: 16,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 2,
  },
  title: {
    fontSize: 18,
    fontWeight: "900",
    color: colors.neutral800,
    marginBottom: 12,
  },
  summaryRow: {
    flexDirection: "row-reverse",
    gap: 8,
    marginBottom: 12,
  },
  summaryItem: {
    flex: 1,
    backgroundColor: colors.neutral50,
    borderWidth: 1,
    borderColor: colors.neutral200,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: "900",
    color: colors.neutral800,
  },
  summaryLabel: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: "700",
    color: colors.neutral500,
  },
  meal: {
    padding: 14,
    borderWidth: 1,
    borderColor: colors.neutral200,
    borderRadius: 14,
    marginBottom: 10,
    backgroundColor: "#fcfdff",
  },
  header: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  headerLeft: {
    flexDirection: "row-reverse",
    gap: 8,
    alignItems: "center",
  },
  iconBubble: {
    width: 28,
    height: 28,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e2e8f0",
  },
  mealTitle: {
    fontWeight: "800",
    color: colors.neutral800,
    fontSize: 14,
  },
  badge: {
    backgroundColor: "#ecfdf5",
    color: "#0f766e",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    fontSize: 12,
  },
  muted: {
    fontSize: 12,
    color: colors.neutral500,
    marginBottom: 4,
  },
  description: {
    fontSize: 14,
    marginBottom: 10,
    color: colors.neutral700,
    lineHeight: 19,
    textAlign: "right",
    writingDirection: "rtl",
  },
  footer: {
    flexDirection: "row-reverse",
    gap: 8,
  },
  metricChip: {
    backgroundColor: colors.neutral100,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: colors.neutral200,
  },
  footerText: {
    fontSize: 12,
    color: colors.neutral700,
    fontWeight: "700",
  },
});
