import { StyleSheet } from "react-native";
import { colors } from "src/styles/colors";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(17, 24, 39, 0.45)",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 24,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.neutral200,
    maxHeight: "92%",
    overflow: "hidden",
  },
  header: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: colors.neutral200,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  title: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.neutral800,
    textAlign: "right",
  },
  closeButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  closeButtonText: {
    fontSize: 22,
    color: colors.neutral500,
    lineHeight: 24,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
  },
  fieldGroup: {
    marginBottom: 12,
  },
  label: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.neutral700,
    marginBottom: 6,
    textAlign: "right",
  },
  input: {
    borderWidth: 1,
    borderColor: colors.neutral200,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: colors.white,
    textAlign: "right",
    color: colors.neutral800,
    fontSize: 14,
  },
  genderRow: {
    flexDirection: "row-reverse",
    gap: 8,
  },
  genderOption: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.neutral200,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  genderOptionSelected: {
    borderColor: colors.primary,
    backgroundColor: "#EFF6FF",
  },
  genderOptionText: {
    color: colors.neutral700,
    fontSize: 13,
    fontWeight: "600",
  },
  genderOptionTextSelected: {
    color: colors.primary,
  },
  errorText: {
    color: colors.danger,
    fontSize: 13,
    marginTop: 2,
    marginBottom: 8,
    textAlign: "right",
  },
  footer: {
    flexDirection: "row-reverse",
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: colors.neutral200,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  secondaryBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.neutral300,
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  secondaryBtnText: {
    color: colors.neutral700,
    fontSize: 14,
    fontWeight: "600",
  },
  primaryBtn: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
  },
  primaryBtnDisabled: {
    backgroundColor: "#93c5fd",
  },
  primaryBtnText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "700",
  },
});
