const { z } = require("zod");
const {
  MessageSenderEnum,
  MessageContentTypeEnum,
  MessageHandledByEnum,
  AIDecisionEnum,
} = require("./enums");

const MessageDto = z.object({
  id: z.string(),
  conversationId: z.string(),

  sender: MessageSenderEnum,
  contentType: MessageContentTypeEnum,
  text: z.string().nullable(),
  mediaUrl: z.string().nullable(),
  mediaMimeType: z.string().nullable(),
  mediaDurationSec: z.number().nullable(),
  mediaThumbnail: z.string().nullable(),
  sourceMessageId: z.string().nullable().optional(),
  autoGenerated: z.boolean().nullable().optional(),

  aiDecision: AIDecisionEnum.nullable(),
  aiSuggestedReply: z.string().nullable(),

  handledAt: z.string().datetime().nullable(),
  handledBy: MessageHandledByEnum.nullable(),

  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime().optional(), 
});

/* =========================
   RESPONSES
========================= */

const MessageResponseDto = z.object({
  data: MessageDto,
});

const MessageListResponseDto = z.object({
  data: z.array(MessageDto),
});

module.exports = {
  MessageDto,
  MessageResponseDto,
  MessageListResponseDto,
};
