/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequestDto"];
                };
            };
            responses: {
                /** @description Successful login */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register new account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequestDto"];
                };
            };
            responses: {
                /** @description Account created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh expired access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New session tokens */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefreshTokenResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully logged out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register MFA device */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description MFA device registered */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify MFA code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MfaVerifyRequestDto"];
                };
            };
            responses: {
                /** @description MFA verified & session created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MfaVerifyResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of enriched client profiles for coach */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of clients */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientsListResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get raw client info from IDM */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Client data retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get full user info */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User info retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserInfoResponseDto"];
                    };
                };
            };
        };
        /** Update user info */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertUserInfoRequestDto"];
                };
            };
            responses: {
                /** @description User info updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete user info record */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User info deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/food": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all food items */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of food items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create new food item */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FoodItemRequestCreateDto"];
                };
            };
            responses: {
                /** @description Food item created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/food/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search food items */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/food/by-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get food categorized */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categorized food list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/food/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update food item */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FoodItemRequestUpdateDto"];
                };
            };
            responses: {
                /** @description Food item updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete food item */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Food item deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all workout templates */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of workout templates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create workout template */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkoutTemplateCreateRequestDto"];
                };
            };
            responses: {
                /** @description Workout template created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get meal template by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Template retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update workout template */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkoutTemplateUpdateRequestDto"];
                };
            };
            responses: {
                /** @description Workout template updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete workout template */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workout template deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/template-menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all template menus */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Template menus list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a new template menu */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TemplateMenuCreateRequestDto"];
                };
            };
            responses: {
                /** @description Template menu created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/template-menus/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get template menu by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Template menu retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update template menu */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Template menu updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete template menu */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Template menu deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client-menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List client menus (coach or client) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Client menus list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a new client menu */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientMenuCreateRequestDto"];
                };
            };
            responses: {
                /** @description Client menu created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client-menus/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update client menu */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ClientMenuUpdateRequestDto"];
                };
            };
            responses: {
                /** @description Client menu updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete client menu */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Client menu deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client-menus/from-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create client menu from template */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientMenuCreateFromTemplateRequestDto"];
                };
            };
            responses: {
                /** @description Client menu created from template */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vitamins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all vitamins */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of vitamins */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a new vitamin */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VitaminCreateRequestDto"];
                };
            };
            responses: {
                /** @description Vitamin created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/day-selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Client sets day type */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DaySelectionCreateRequestDto"];
                };
            };
            responses: {
                /** @description Day type updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DaySelectionResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/meal-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Client logs a meal */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MealLogCreateRequestDto"];
                };
            };
            responses: {
                /** @description Meal logged */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MealLogResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/workout-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Client logs workout of the day */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkoutLogCreateRequestDto"];
                };
            };
            responses: {
                /** @description Workout logged */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkoutLogResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/workout-log/{logId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Client updates workout log */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    logId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkoutLogUpdateRequestDto"];
                };
            };
            responses: {
                /** @description Workout log updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkoutLogResponseDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/workout-log/exercise/{exerciseLogId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Client updates a single exercise entry */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exerciseLogId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Exercise entry updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/tracking/weight-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Client logs body weight */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WeightLogCreateRequestDto"];
                };
            };
            responses: {
                /** @description Weight logged */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WeightLogResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/day-selection/today/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coach views today's day type for the client */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clientId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Today's day selection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DaySelectionTodayResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/meal-log/history/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coach views meal log history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clientId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Meal log history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MealLogHistoryResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/workout-log/history/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coach views workout log history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clientId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workout log history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkoutLogHistoryResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/weight-log/history/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coach views weight log history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clientId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Weight log history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WeightHistoryResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all exercises */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of exercises */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create new exercise */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExerciseCreateRequestDto"];
                };
            };
            responses: {
                /** @description Exercise created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get exercise by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Exercise retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update exercise */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExerciseUpdateRequestDto"];
                };
            };
            responses: {
                /** @description Exercise updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete exercise */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Exercise deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload exercise video */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description Video uploaded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve uploaded exercise assets */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Assets served */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coach fetches all programs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of workout programs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs/{programId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coach fetches a single program */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    programId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workout program retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{clientId}/workout-programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Client or coach fetch client programs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clientId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Client workout programs list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Coach assigns program to client */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clientId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkoutProgramCreateRequestDto"];
                };
            };
            responses: {
                /** @description Workout program created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{clientId}/workout-programs/{programId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch specific program by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clientId: string;
                    programId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Client program retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Coach updates client's workout program */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clientId: string;
                    programId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkoutProgramUpdateRequestDto"];
                };
            };
            responses: {
                /** @description Workout program updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Coach deletes program */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clientId: string;
                    programId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workout program deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ClientListItemDto: {
            id: string;
            name: string;
            phone: string | null;
            email: string | null;
            /** Format: url */
            profileImageUrl: string | null;
            gender: string | null;
            age: number | null;
            height: number | null;
            weight: number | null;
            goals: unknown;
            activityLevel: unknown;
            creationDate: string | null;
            city: string | null;
            address: string | null;
        };
        ClientsListResponseDto: {
            data: {
                id: string;
                name: string;
                phone: string | null;
                email: string | null;
                /** Format: url */
                profileImageUrl: string | null;
                gender: string | null;
                age: number | null;
                height: number | null;
                weight: number | null;
                goals: unknown;
                activityLevel: unknown;
                creationDate: string | null;
                city: string | null;
                address: string | null;
            }[];
        };
        LoginRequestDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponseDto: {
            user: {
                id: string;
                /** Format: email */
                email: string;
                firstName: string | null;
                phone?: string | null;
                lastName: string | null;
                /** @enum {string} */
                status: "active" | "locked";
                role: string;
            };
            sessionId: string;
            tokens: {
                accessToken: string;
                refreshToken: string;
                accessTokenExp?: number;
                refreshTokenExp?: number;
            };
        };
        LogoutRequestDto: Record<string, never>;
        LogoutResponseDto: {
            data: {
                success: boolean;
            };
        };
        MfaRegisterRequestDto: Record<string, never>;
        MfaRegisterResponseDto: {
            data: {
                id: string;
                type: string;
                userId: string;
            };
        };
        MfaVerifyRequestDto: {
            code: string;
        };
        MfaVerifyResponseDto: {
            data: {
                accessToken: string;
                expiresAt: string;
                tokenType: string;
            };
        };
        RefreshTokenResponseDto: {
            data: {
                accessToken: string;
                expiresAt: string;
                tokenType: string;
            };
        };
        RegisterRequestDto: {
            /** Format: email */
            email: string;
            phone: string;
            firstName: string;
            lastName: string;
            password: string;
            /** @enum {string} */
            role?: "trainer" | "client" | "admin";
        };
        RegisterResponseDto: {
            data: {
                message: string;
                id: Record<string, never>;
            };
        };
        UpsertUserInfoRequestDto: {
            dateOfBirth?: string;
            gender?: string;
            address?: string;
            city?: string;
            /** Format: url */
            profileImageUrl?: string;
            height?: number;
            age?: number;
        };
        UpsertUserInfoResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            status: Record<string, never>;
            /** Format: datetime */
            dateOfBirth?: string | null;
            gender?: string | null;
            address?: string | null;
            city?: string | null;
            /** Format: url */
            profileImageUrl?: string | null;
            height?: number | null;
            age?: number | null;
            /** Format: datetime */
            createdAt: string;
            /** Format: datetime */
            updatedAt: string;
        };
        UserInfoResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            status: Record<string, never>;
            /** Format: datetime */
            dateOfBirth?: string | null;
            gender?: string | null;
            address?: string | null;
            city?: string | null;
            /** Format: url */
            profileImageUrl?: string | null;
            height?: number | null;
            age?: number | null;
            /** Format: datetime */
            createdAt: string;
            /** Format: datetime */
            updatedAt: string;
        };
        ClientMenuCreateFromTemplateRequestDto: {
            templateMenuId: string;
            clientId: string;
            coachId: string;
            name?: string;
            selectedOptions?: {
                templateMealId: string;
                optionId: string;
            }[];
        };
        ClientMenuCreateRequestDto: {
            clientId: string;
            name: string;
            type: string;
            notes?: string | null;
            startDate?: string;
            endDate?: string;
        };
        ClientMenuResponseDto: {
            id: string;
            name: string;
            type: string;
            notes: string | null;
            isActive: boolean;
            meals: {
                id: string;
                name: string;
                selectedOptionId: string | null;
                options: {
                    id: string;
                    name: string | null;
                    orderIndex: number;
                    mealTemplate: {
                        id: string;
                        name: string;
                        kind: string;
                        items: {
                            id: string;
                            role: string;
                            defaultGrams: number;
                            notes: string | null;
                            foodItem: {
                                id: string;
                                name: string;
                                caloriesPer100g: number | null;
                            };
                        }[];
                    };
                }[];
                items: {
                    id: string;
                    quantity: number;
                    calories: number;
                    notes: string | null;
                    foodItem: {
                        id: string;
                        name: string;
                        caloriesPer100g: number | null;
                    };
                }[];
            }[];
            vitamins: {
                id: string;
                vitaminId: string | null;
                name: string;
                description: string | null;
            }[];
        };
        ClientMenuUpdateRequestDto: {
            name?: string;
            type?: string;
            notes?: string | null;
            isActive?: boolean;
            startDate?: string;
            endDate?: string;
            mealsToAdd?: {
                templateId: string;
                name?: string;
            }[];
            mealsToUpdate?: unknown;
            mealsToDelete?: {
                id: string;
            }[];
            mealOptionsToAdd?: unknown;
            mealOptionsToDelete?: unknown;
            itemsToAdd?: unknown;
            itemsToUpdate?: unknown;
            itemsToDelete?: unknown;
            vitaminsToAdd?: unknown;
            vitaminsToUpdate?: unknown;
            vitaminsToDelete?: unknown;
        };
        FoodItemRequestCreateDto: {
            name: string;
            description?: string | null;
            category?: string | null;
            caloriesPer100g?: number | null;
            proteinPer100g?: number | null;
        };
        FoodItemRequestUpdateDto: {
            name?: string;
            description?: string | null;
            category?: string | null;
            caloriesPer100g?: number | null;
            proteinPer100g?: number | null;
        };
        FoodItemResponseDto: {
            id: string;
            name: string;
            description: string | null;
            category: string | null;
            caloriesPer100g: number | null;
            proteinPer100g: number | null;
        };
        MealTemplateCreateRequestDto: {
            name: string;
            kind: string;
            totalCalories?: number;
            items?: {
                foodItemId: string;
                role: string;
                defaultGrams?: number;
                defaultCalories?: number | null;
                notes?: string | null;
            }[];
        };
        MealTemplateResponseDto: {
            id: string;
            name: string;
            kind: string;
            totalCalories: number;
            items: {
                id: string;
                role: string;
                defaultGrams: number;
                defaultCalories: number | null;
                notes: string | null;
                foodItem: {
                    id: string;
                    name: string;
                    caloriesPer100g: number | null;
                };
            }[];
        };
        MealTemplateUpdateRequestDto: {
            name?: string;
            kind?: string;
            totalCalories?: number;
            itemsToAdd?: {
                foodItemId: string;
                role: string;
                defaultGrams?: number;
                defaultCalories?: number | null;
                notes?: string | null;
            }[];
            itemsToUpdate?: {
                id: string;
                foodItemId?: string;
                role?: string;
                defaultGrams?: number;
                defaultCalories?: number | null;
                notes?: string | null;
            }[];
            itemsToDelete?: {
                id: string;
            }[];
        };
        TemplateMenuCreateRequestDto: {
            name: string;
            dayType: string;
            notes?: string | null;
            meals?: {
                name: string;
                options?: {
                    mealTemplateId: string;
                    name?: string | null;
                    orderIndex?: number;
                }[];
            }[];
            vitamins?: {
                vitaminId?: string | null;
                name: string;
                description?: string | null;
            }[];
        };
        TemplateMenuResponseDto: {
            id: string;
            name: string;
            coachId: string;
            dayType: string;
            notes: string | null;
            totalCalories: number;
            meals: {
                id: string;
                name: string;
                totalCalories?: number | null;
                selectedOptionId: string | null;
                options: {
                    id: string;
                    name: string | null;
                    orderIndex: number;
                    mealTemplate: {
                        id: string;
                        name: string;
                        kind: string;
                        totalCalories?: number | null;
                        items: {
                            id: string;
                            role: string;
                            defaultGrams: number;
                            notes: string | null;
                            foodItem: {
                                id: string;
                                name: string;
                                caloriesPer100g: number | null;
                            };
                        }[];
                    };
                }[];
            }[];
            vitamins: {
                id: string;
                vitaminId: string | null;
                name: string;
                description: string | null;
            }[];
        };
        TemplateMenuUpdateRequestDto: {
            name?: string;
            dayType?: string;
            notes?: string | null;
            totalCalories?: number;
            mealsToAdd?: {
                name: string;
                totalCalories?: number | null;
                orderIndex?: number;
            }[];
            mealsToUpdate?: {
                id: string;
                name?: string;
                selectedOptionId?: string | null;
                totalCalories?: number | null;
            }[];
            mealsToDelete?: {
                id: string;
            }[];
            mealOptionsToAdd?: {
                mealId: string;
                mealTemplateId?: string;
                name?: string | null;
                orderIndex?: number;
            }[];
            mealOptionsToDelete?: {
                id: string;
            }[];
            vitaminsToAdd?: {
                vitaminId?: string | null;
                name: string;
                description?: string | null;
            }[];
            vitaminsToDelete?: {
                id: string;
            }[];
        };
        VitaminCreateRequestDto: {
            name: string;
            description?: string | null;
        };
        VitaminResponseDto: {
            id: string;
            name: string;
            description: string | null;
        };
        VitaminUpdateRequestDto: {
            name?: string;
            description?: string | null;
        };
        DaySelectionCreateRequestDto: {
            /** @enum {string} */
            dayType: "LOW" | "HIGH" | "MEDIUM" | "REST";
            /** Format: datetime */
            date?: string;
        };
        DaySelectionResponseDto: {
            data: {
                id: string;
                clientId: string;
                /** Format: datetime */
                date: string;
                /** @enum {string} */
                dayType: "LOW" | "HIGH" | "MEDIUM" | "REST";
                /** Format: datetime */
                changedAt: string;
            };
        };
        DaySelectionTodayResponseDto: {
            data: {
                id: string;
                clientId: string;
                /** Format: datetime */
                date: string;
                /** @enum {string} */
                dayType: "LOW" | "HIGH" | "MEDIUM" | "REST";
                /** Format: datetime */
                changedAt: string;
            };
        };
        /** @enum {string} */
        DayTypeEnum: "LOW" | "HIGH" | "MEDIUM" | "REST";
        MealLogCreateRequestDto: {
            /** Format: datetime */
            date?: string;
            calories: number;
            protein: number;
            carbs: number;
            fat: number;
            description?: string;
            matchedMenuItemId?: string;
            /** @enum {string} */
            dayType: "LOW" | "HIGH" | "MEDIUM" | "REST";
        };
        MealLogHistoryResponseDto: {
            data: {
                id: string;
                clientId: string;
                /** Format: datetime */
                date: string;
                /** @enum {string} */
                dayType: "LOW" | "HIGH" | "MEDIUM" | "REST";
                calories: number;
                protein: number;
                carbs: number;
                fat: number;
                description: string | null;
                matchedMenuItemId: string | null;
                /** Format: datetime */
                loggedAt?: string;
            }[];
        };
        MealLogResponseDto: {
            data: {
                id: string;
                clientId: string;
                /** Format: datetime */
                date: string;
                /** @enum {string} */
                dayType: "LOW" | "HIGH" | "MEDIUM" | "REST";
                calories: number;
                protein: number;
                carbs: number;
                fat: number;
                description: string | null;
                matchedMenuItemId: string | null;
                /** Format: datetime */
                loggedAt?: string;
            };
        };
        WeightHistoryResponseDto: {
            data: {
                id: string;
                clientId: string;
                /** Format: datetime */
                date: string;
                weightKg: number;
                notes: string | null;
            }[];
        };
        WeightLogCreateRequestDto: {
            /** Format: datetime */
            date?: string;
            weightKg: number;
            notes?: string;
        };
        WeightLogResponseDto: {
            data: {
                id: string;
                clientId: string;
                /** Format: datetime */
                date: string;
                weightKg: number;
                notes: string | null;
            };
        };
        WorkoutLogCreateRequestDto: {
            /** Format: datetime */
            date?: string;
            workoutType: string;
            /** @enum {string} */
            effortLevel: "EASY" | "NORMAL" | "HARD" | "FAILED" | "SKIPPED";
            notes?: string;
            exercises: {
                exerciseName: string;
                weight?: number | null;
            }[];
        };
        WorkoutLogHistoryResponseDto: {
            data: {
                id: string;
                clientId: string;
                /** Format: datetime */
                date: string;
                workoutType: string;
                /** @enum {string} */
                effortLevel: "EASY" | "NORMAL" | "HARD" | "FAILED" | "SKIPPED";
                notes: string | null;
                /** Format: datetime */
                loggedAt?: string;
                exercises: {
                    id: string;
                    workoutLogId: string;
                    exerciseName: string;
                    weight: number | null;
                }[];
            }[];
        };
        WorkoutLogResponseDto: {
            data: {
                id: string;
                clientId: string;
                /** Format: datetime */
                date: string;
                workoutType: string;
                /** @enum {string} */
                effortLevel: "EASY" | "NORMAL" | "HARD" | "FAILED" | "SKIPPED";
                notes: string | null;
                /** Format: datetime */
                loggedAt?: string;
                exercises: {
                    id: string;
                    workoutLogId: string;
                    exerciseName: string;
                    weight: number | null;
                }[];
            };
        };
        WorkoutLogUpdateRequestDto: {
            workoutType?: string;
            /** @enum {string} */
            effortLevel?: "EASY" | "NORMAL" | "HARD" | "FAILED" | "SKIPPED";
            notes?: string;
            exercises?: {
                id: string;
                exerciseName: string;
                weight?: number | null;
            }[];
        };
        /** @enum {string} */
        BodyTypeEnum: "ECTO" | "ENDO";
        ExerciseCreateRequestDto: {
            name: string;
            description?: string;
            notes?: string;
            /** Format: url */
            videoUrl?: string;
            /** @enum {string} */
            muscleGroup: "CHEST" | "BACK" | "SHOULDERS" | "LEGS" | "GLUTES" | "ARMS" | "BICEPS" | "TRICEPS" | "ABS" | "FULL_BODY";
            /** @enum {string} */
            gender?: "MALE" | "FEMALE";
            /** @enum {string} */
            bodyType?: "ECTO" | "ENDO";
            workoutTypes?: ("A" | "B" | "FBW" | "UPPER" | "LOWER" | "GLUTES" | "HIIT" | "PUSH" | "PULL" | "LEGS")[];
            equipment?: string;
            difficulty?: string;
        };
        ExerciseResponseDto: {
            id: string;
            name: string;
            description: string | null;
            notes: string | null;
            videoUrl: string | null;
            muscleGroup: string;
            gender: string | null;
            bodyType: string | null;
            workoutTypes: string[];
            equipment: string | null;
            difficulty: string | null;
            createdByCoachId: string | null;
            createdAt: string;
            updatedAt: string;
        };
        ExerciseUpdateRequestDto: {
            name?: string;
            description?: string;
            notes?: string;
            /** Format: url */
            videoUrl?: string;
            /** @enum {string} */
            muscleGroup?: "CHEST" | "BACK" | "SHOULDERS" | "LEGS" | "GLUTES" | "ARMS" | "BICEPS" | "TRICEPS" | "ABS" | "FULL_BODY";
            /** @enum {string} */
            gender?: "MALE" | "FEMALE";
            /** @enum {string} */
            bodyType?: "ECTO" | "ENDO";
            workoutTypes?: ("A" | "B" | "FBW" | "UPPER" | "LOWER" | "GLUTES" | "HIIT" | "PUSH" | "PULL" | "LEGS")[];
            equipment?: string;
            difficulty?: string;
        };
        /** @enum {string} */
        GenderEnum: "MALE" | "FEMALE";
        /** @enum {string} */
        MuscleGroupEnum: "CHEST" | "BACK" | "SHOULDERS" | "LEGS" | "GLUTES" | "ARMS" | "BICEPS" | "TRICEPS" | "ABS" | "FULL_BODY";
        WorkoutProgramCreateRequestDto: {
            name: string;
            clientId: string;
            coachId: string;
            templateId?: string;
            exercises: Record<string, never>;
        };
        WorkoutProgramExerciseCreateDto: {
            exerciseId: string;
            sets: number;
            reps: string;
            weight?: number | null;
            rest?: number | null;
            order: number;
            notes?: string | null;
        };
        WorkoutProgramExerciseDeleteDto: {
            id: string;
        };
        WorkoutProgramExerciseUpdateDto: {
            id: string;
            exerciseId?: string;
            sets?: number;
            reps?: string;
            weight?: number | null;
            rest?: number | null;
            order?: number;
            notes?: string | null;
        };
        WorkoutProgramResponseDto: {
            id: string;
            name: string;
            clientId: string;
            coachId: string;
            templateId?: string | null;
            createdAt: string;
            updatedAt: string;
            exercises: {
                id: string;
                programId: string;
                exerciseId: string;
                sets: number;
                reps: string;
                weight: number | null;
                rest: number | null;
                order: number;
                notes: string | null;
                createdAt: string;
                updatedAt: string;
            }[];
        };
        WorkoutProgramUpdateRequestDto: {
            name?: string;
            exercisesToAdd?: {
                exerciseId: string;
                sets: number;
                reps: string;
                weight?: number | null;
                rest?: number | null;
                order: number;
                notes?: string | null;
            }[];
            exercisesToUpdate?: {
                id: string;
                exerciseId?: string;
                sets?: number;
                reps?: string;
                weight?: number | null;
                rest?: number | null;
                order?: number;
                notes?: string | null;
            }[];
            exercisesToDelete?: {
                id: string;
            }[];
        };
        WorkoutTemplateCreateRequestDto: {
            /** @enum {string} */
            gender: "MALE" | "FEMALE";
            level: number;
            /** @enum {string|null} */
            bodyType?: "ECTO" | "ENDO" | null;
            workoutType: string;
            muscleGroups: string[];
            name?: string | null;
            notes?: string | null;
        };
        WorkoutTemplateResponseDto: {
            id: string;
            /** @enum {string} */
            gender: "MALE" | "FEMALE";
            level: number;
            /** @enum {string|null} */
            bodyType: "ECTO" | "ENDO" | null;
            workoutType: string;
            muscleGroups: string[];
            name: string | null;
            notes: string | null;
        };
        WorkoutTemplateUpdateRequestDto: {
            /** @enum {string} */
            gender?: "MALE" | "FEMALE";
            level?: number;
            /** @enum {string|null} */
            bodyType?: "ECTO" | "ENDO" | null;
            workoutType?: string;
            muscleGroups?: string[];
            name?: string | null;
            notes?: string | null;
        };
        /** @enum {string} */
        WorkoutTypeEnum: "A" | "B" | "FBW" | "UPPER" | "LOWER" | "GLUTES" | "HIIT" | "PUSH" | "PULL" | "LEGS";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
