/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/assistant` | `/assistant`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/nutrition` | `/nutrition`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownInputParams; } | { pathname: `/login/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/messages`; params?: Router.UnknownInputParams; } | { pathname: `/nutrition/report`; params?: Router.UnknownInputParams; } | { pathname: `/nutrition/meal/[mealId]`, params: Router.UnknownInputParams & { mealId: string | number; } } | { pathname: `/workout/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/workout/active/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/workout/summary/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/assistant` | `/assistant`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/nutrition` | `/nutrition`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownOutputParams; } | { pathname: `/login/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/messages`; params?: Router.UnknownOutputParams; } | { pathname: `/nutrition/report`; params?: Router.UnknownOutputParams; } | { pathname: `/nutrition/meal/[mealId]`, params: Router.UnknownOutputParams & { mealId: string; } } | { pathname: `/workout/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/workout/active/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/workout/summary/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/assistant${`?${string}` | `#${string}` | ''}` | `/assistant${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/community${`?${string}` | `#${string}` | ''}` | `/community${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/nutrition${`?${string}` | `#${string}` | ''}` | `/nutrition${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/workout${`?${string}` | `#${string}` | ''}` | `/workout${`?${string}` | `#${string}` | ''}` | `/login/forgot-password${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/messages${`?${string}` | `#${string}` | ''}` | `/nutrition/report${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/assistant` | `/assistant`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/nutrition` | `/nutrition`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownInputParams; } | { pathname: `/login/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/messages`; params?: Router.UnknownInputParams; } | { pathname: `/nutrition/report`; params?: Router.UnknownInputParams; } | `/nutrition/meal/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/workout/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/workout/active/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/workout/summary/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/nutrition/meal/[mealId]`, params: Router.UnknownInputParams & { mealId: string | number; } } | { pathname: `/workout/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/workout/active/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/workout/summary/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
